import { APP_LOCALE, formatTemplate, resolveLocalizedText, type AppLocale, type LocalizedText } from "./app-locale";

type ControlledCopyEntry = {
  en: string;
  zh: string;
  intent: string;
  toneNote: string;
  usageScope: string;
};

export const CONTROLLED_COPY = {
  "page.books.title": {
    en: "Books",
    zh: "书架",
    intent: "Page title for the main bookshelf view.",
    toneNote: "Plain, utilitarian, neutral.",
    usageScope: "Document titles and bookshelf header.",
  },
  "page.marks.title": {
    en: "My Marks",
    zh: "我的标记",
    intent: "Page title for the workspace marks view.",
    toneNote: "Plain, utilitarian, neutral.",
    usageScope: "Document titles and marks page header.",
  },
  "page.upload.title": {
    en: "Upload",
    zh: "上传",
    intent: "Page title for upload-related routes.",
    toneNote: "Short and functional.",
    usageScope: "Document titles.",
  },
  "page.analysis.title": {
    en: "Reading in progress",
    zh: "分析中",
    intent: "Page title for legacy analysis routes redirecting to active reading.",
    toneNote: "Short and stateful.",
    usageScope: "Document titles.",
  },
  "page.book.title": {
    en: "Book overview",
    zh: "书籍详情",
    intent: "Page title for the canonical book overview page.",
    toneNote: "Short and descriptive.",
    usageScope: "Document titles and page-level references.",
  },
  "page.chapter.title": {
    en: "Chapter reading",
    zh: "章节深读",
    intent: "Page title for the chapter reading workspace.",
    toneNote: "Short and descriptive.",
    usageScope: "Document titles.",
  },
  "layout.tagline": {
    en: "Deep reading workspace",
    zh: "深读工作台",
    intent: "Short brand-supporting tagline shown under the product name on the landing page.",
    toneNote: "Concise, quiet, product-like.",
    usageScope: "Top navigation brand area on the landing page.",
  },
  "state.loading.generic": {
    en: "Loading...",
    zh: "加载中...",
    intent: "Generic loading state fallback.",
    toneNote: "Brief and neutral.",
    usageScope: "Shared page-state loading card.",
  },
  "state.error.title": {
    en: "Unable to load this page",
    zh: "页面暂时无法加载",
    intent: "Generic error-state headline.",
    toneNote: "Calm and non-alarming.",
    usageScope: "Shared page-state error card.",
  },
  "state.error.backendUnavailable.title": {
    en: "Backend is unavailable",
    zh: "后端服务暂时不可用",
    intent: "Shared headline when the API cannot be reached at all.",
    toneNote: "Direct, calm, and diagnostic.",
    usageScope: "Primary page-level failures caused by the backend being offline.",
  },
  "state.error.backendUnavailable.message": {
    en: "The reading service looks offline. Retry after it reconnects.",
    zh: "阅读服务似乎已离线。待它重新连接后再试。",
    intent: "Shared explanatory copy when the API host is unreachable.",
    toneNote: "Plain and reassuring.",
    usageScope: "Primary page-level failures caused by the backend being offline.",
  },
  "action.retry": {
    en: "Retry",
    zh: "重试",
    intent: "Retry action for recoverable failures.",
    toneNote: "Direct and action-oriented.",
    usageScope: "Shared error and sync controls.",
  },
  "bookshelf.error.title": {
    en: "Bookshelf is unavailable",
    zh: "书架暂时不可用",
    intent: "Bookshelf page load failure headline.",
    toneNote: "Calm and informative.",
    usageScope: "Bookshelf error state.",
  },
  "bookshelf.error.message": {
    en: "We could not load your books right now.",
    zh: "当前无法加载你的书架内容。",
    intent: "Bookshelf page load failure body copy.",
    toneNote: "Calm and informative.",
    usageScope: "Bookshelf error state.",
  },
  "bookshelf.empty.title": {
    en: "No books yet",
    zh: "还没有书",
    intent: "Empty bookshelf headline.",
    toneNote: "Encouraging and concise.",
    usageScope: "Bookshelf empty state.",
  },
  "bookshelf.empty.message": {
    en: "Upload an EPUB to add the first book to this workspace.",
    zh: "上传一本 EPUB，把第一本书加入这个工作台。",
    intent: "Empty bookshelf body copy.",
    toneNote: "Inviting and concise.",
    usageScope: "Bookshelf empty state.",
  },
  "bookshelf.count.summary": {
    en: "{books} books · {marks} total marks",
    zh: "{books} 本书 · {marks} 个标记",
    intent: "Shelf-level summary under the main page title.",
    toneNote: "Compact and factual.",
    usageScope: "Bookshelf header.",
  },
  "bookshelf.action.addBook": {
    en: "Add book",
    zh: "添加新书",
    intent: "Primary action to open the upload flow.",
    toneNote: "Short CTA.",
    usageScope: "Bookshelf and empty-state primary action.",
  },
  "bookshelf.action.openMarks": {
    en: "My marks",
    zh: "我的标记",
    intent: "Secondary header action leading to marks.",
    toneNote: "Short navigation CTA.",
    usageScope: "Bookshelf header.",
  },
  "bookshelf.upload.title": {
    en: "Add a new book",
    zh: "添加一本新书",
    intent: "Upload dialog title from the bookshelf.",
    toneNote: "Direct and neutral.",
    usageScope: "Bookshelf upload dialog.",
  },
  "bookshelf.upload.description": {
    en: "Upload an EPUB and 书虫 will parse the book structure so deep reading can begin whenever you're ready.",
    zh: "上传 EPUB 文件，书虫会解析全书结构，准备好后可以随时开始深读。",
    intent: "Upload dialog explanatory copy.",
    toneNote: "Warm but concise.",
    usageScope: "Bookshelf upload dialog.",
  },
  "bookshelf.confirmation.title": {
    en: "“{title}” is now on your shelf",
    zh: "《{title}》已添加到书架",
    intent: "Deferred upload success dialog title.",
    toneNote: "Pleasant and clear.",
    usageScope: "Bookshelf deferred-upload confirmation dialog.",
  },
  "bookshelf.confirmation.description": {
    en: "The original chapter outline is ready with {count} chapters. Start deep reading now, or just return to the shelf for later.",
    zh: "原书目录已解析完成，共 {count} 章。要现在开始深读，还是先只进入书架？",
    intent: "Deferred upload success dialog explanation.",
    toneNote: "Clear choice framing.",
    usageScope: "Bookshelf deferred-upload confirmation dialog.",
  },
  "bookshelf.confirmation.later": {
    en: "Return to shelf",
    zh: "只进入书架",
    intent: "Deferred upload choice to postpone reading.",
    toneNote: "Quiet secondary action.",
    usageScope: "Bookshelf deferred-upload confirmation dialog.",
  },
  "bookshelf.confirmation.start": {
    en: "Start deep reading",
    zh: "开始深读",
    intent: "Deferred upload choice to start reading immediately.",
    toneNote: "Primary action, confident but not hype.",
    usageScope: "Bookshelf deferred-upload confirmation dialog and overview CTA.",
  },
  "upload.dialog.close": {
    en: "Close upload dialog",
    zh: "关闭上传对话框",
    intent: "Accessible label for the upload dialog close button.",
    toneNote: "Purely functional.",
    usageScope: "Upload dialog aria-label.",
  },
  "upload.dialog.drop": {
    en: "Drag & drop your EPUB here",
    zh: "将 EPUB 拖放到这里",
    intent: "Primary dropzone prompt.",
    toneNote: "Clear and inviting.",
    usageScope: "Upload dialog dropzone.",
  },
  "upload.dialog.dropActive": {
    en: "Drop your file here",
    zh: "把文件放在这里",
    intent: "Dropzone prompt while dragging.",
    toneNote: "Immediate and direct.",
    usageScope: "Upload dialog dropzone.",
  },
  "upload.dialog.release": {
    en: "Release to upload",
    zh: "松手即可上传",
    intent: "Dropzone secondary prompt while dragging.",
    toneNote: "Short and immediate.",
    usageScope: "Upload dialog dropzone.",
  },
  "upload.dialog.browse": {
    en: "browse files",
    zh: "浏览文件",
    intent: "Secondary inline action in the upload dropzone.",
    toneNote: "Short and lightweight.",
    usageScope: "Upload dialog dropzone.",
  },
  "upload.dialog.supports": {
    en: "Supports .epub format",
    zh: "支持 .epub 格式",
    intent: "Upload format support hint.",
    toneNote: "Informational.",
    usageScope: "Upload dialog footer.",
  },
  "upload.status.uploading": {
    en: "Uploading EPUB...",
    zh: "正在上传 EPUB...",
    intent: "Progress text while the file upload is in flight.",
    toneNote: "Purely functional.",
    usageScope: "Upload action status text.",
  },
  "upload.status.preparing": {
    en: "Preparing for deep reading...",
    zh: "正在准备深读流程...",
    intent: "Progress text after immediate upload is accepted.",
    toneNote: "Functional and anticipatory.",
    usageScope: "Upload action status text.",
  },
  "upload.status.parsingOutline": {
    en: "Parsing chapter outline...",
    zh: "正在解析章节目录...",
    intent: "Deferred upload outline preparation status.",
    toneNote: "Functional and concise.",
    usageScope: "Upload action status text.",
  },
  "upload.status.starting": {
    en: "Starting deep reading...",
    zh: "正在开始深读...",
    intent: "Progress text when confirming immediate start after upload.",
    toneNote: "Functional and concise.",
    usageScope: "Upload action status text.",
  },
  "upload.error.failed": {
    en: "Upload failed.",
    zh: "上传失败。",
    intent: "Generic upload failure fallback.",
    toneNote: "Short and factual.",
    usageScope: "Upload action error fallback.",
  },
  "upload.error.slow": {
    en: "This upload is taking longer than expected.",
    zh: "上传耗时比预期更长。",
    intent: "Upload polling timeout fallback.",
    toneNote: "Calm and factual.",
    usageScope: "Upload action error fallback.",
  },
  "marks.loading": {
    en: "Loading your marks...",
    zh: "正在加载你的标记...",
    intent: "Marks page loading title.",
    toneNote: "Neutral.",
    usageScope: "Marks page loading card.",
  },
  "marks.error.title": {
    en: "Marks page is unavailable",
    zh: "标记页暂时不可用",
    intent: "Marks page error title.",
    toneNote: "Calm and informative.",
    usageScope: "Marks page error state.",
  },
  "marks.error.message": {
    en: "We could not load your saved marks right now.",
    zh: "当前无法加载已保存的标记。",
    intent: "Marks page error body copy.",
    toneNote: "Calm and informative.",
    usageScope: "Marks page error state.",
  },
  "marks.subtitle": {
    en: "Resonance, blindspot, and bookmark reactions saved across the whole workspace",
    zh: "汇总整个工作区里保存的共鸣、盲点和书签标记。",
    intent: "Marks page subtitle.",
    toneNote: "Explains scope, still concise.",
    usageScope: "Marks page header.",
  },
  "marks.empty.title": {
    en: "No marks yet",
    zh: "还没有标记",
    intent: "Marks page empty headline.",
    toneNote: "Encouraging and concise.",
    usageScope: "Marks page empty state.",
  },
  "marks.empty.message": {
    en: "Review completed chapter pages and use the mark controls on reactions to save them here.",
    zh: "先去浏览已完成章节，并在反应卡片上使用标记按钮，这里就会出现内容。",
    intent: "Marks page empty body copy.",
    toneNote: "Action-guiding.",
    usageScope: "Marks page empty state.",
  },
  "marks.savedSummary": {
    en: "{count} saved marks",
    zh: "{count} 个已保存标记",
    intent: "Per-book saved mark count.",
    toneNote: "Compact and factual.",
    usageScope: "Marks page book grouping header.",
  },
  "marks.action.openBook": {
    en: "Open book",
    zh: "打开本书",
    intent: "Action to open the parent book overview from marks pages.",
    toneNote: "Short and direct.",
    usageScope: "Marks page and grouped book mark panels.",
  },
  "marks.action.openChapter": {
    en: "Open chapter",
    zh: "打开章节",
    intent: "Action to open the parent chapter from marks views.",
    toneNote: "Short and direct.",
    usageScope: "Marks page and grouped book mark panels.",
  },
  "overview.loading": {
    en: "Loading book details...",
    zh: "正在加载书籍详情...",
    intent: "Book overview loading title.",
    toneNote: "Neutral.",
    usageScope: "Book overview loading card.",
  },
  "overview.error.title": {
    en: "Book overview is unavailable",
    zh: "书籍总览暂时不可用",
    intent: "Book overview error title.",
    toneNote: "Calm and informative.",
    usageScope: "Book overview error state.",
  },
  "overview.error.message": {
    en: "We could not load this book right now.",
    zh: "当前无法加载这本书。",
    intent: "Book overview error body copy.",
    toneNote: "Calm and informative.",
    usageScope: "Book overview error state.",
  },
  "overview.error.start": {
    en: "Could not start deep reading.",
    zh: "无法开始深读。",
    intent: "Fallback error after trying to start deep reading from the overview.",
    toneNote: "Short and factual.",
    usageScope: "Book overview start action error state.",
  },
  "overview.error.resume": {
    en: "Could not continue deep reading.",
    zh: "无法继续深读。",
    intent: "Fallback error after trying to resume deep reading from the overview.",
    toneNote: "Short and factual.",
    usageScope: "Book overview resume action error state.",
  },
  "overview.cta.start": {
    en: "Start deep reading",
    zh: "开始深读",
    intent: "Primary CTA for books that have not started reading.",
    toneNote: "Confident primary action.",
    usageScope: "Book overview header actions.",
  },
  "overview.cta.resume": {
    en: "Resume deep reading",
    zh: "继续深读",
    intent: "Primary CTA for paused books.",
    toneNote: "Confident recovery action.",
    usageScope: "Book overview header actions.",
  },
  "overview.cta.running": {
    en: "Deep reading in progress",
    zh: "深读进行中",
    intent: "Passive running-state badge in the header.",
    toneNote: "Calm, live-status wording.",
    usageScope: "Book overview header actions.",
  },
  "overview.cta.downloadSource": {
    en: "Download source EPUB",
    zh: "下载原始 EPUB",
    intent: "Download action for the uploaded source file.",
    toneNote: "Purely functional.",
    usageScope: "Book overview header actions.",
  },
  "overview.section.readyToStart": {
    en: "Ready to Start",
    zh: "准备开始",
    intent: "Eyebrow label for not-started overview state.",
    toneNote: "Short and energizing.",
    usageScope: "Book overview status band.",
  },
  "overview.ready.title.ready": {
    en: "The original chapter outline is ready",
    zh: "原书目录已就绪",
    intent: "Headline when the base chapter outline is ready before deep reading starts.",
    toneNote: "Factual and reassuring.",
    usageScope: "Not-started book overview state.",
  },
  "overview.ready.title.preparing": {
    en: "Preparing the chapter outline",
    zh: "正在准备目录",
    intent: "Headline when the base chapter outline is still being prepared.",
    toneNote: "Factual and temporary.",
    usageScope: "Not-started book overview state.",
  },
  "overview.ready.description": {
    en: "Semantic segmentation begins automatically after deep reading starts. This page first helps you review the original chapter structure of the book.",
    zh: "语义段落切分会在开始深读后自动进行，当前页先帮助你确认整本书的原始章节结构。",
    intent: "Not-started explanatory copy.",
    toneNote: "Helpful and calm.",
    usageScope: "Not-started book overview state.",
  },
  "overview.metric.parsedChapters": {
    en: "Parsed chapters",
    zh: "已解析章节",
    intent: "Metric label for base chapter outline count.",
    toneNote: "Short and factual.",
    usageScope: "Not-started book overview state.",
  },
  "overview.section.completed": {
    en: "Completed Overview",
    zh: "完成概览",
    intent: "Eyebrow label for completed overview summary.",
    toneNote: "Short and calm.",
    usageScope: "Completed book overview state.",
  },
  "overview.metric.completedChapters": {
    en: "Completed chapters",
    zh: "已完成章节",
    intent: "Metric label for completed chapter count.",
    toneNote: "Short and factual.",
    usageScope: "Completed book overview state.",
  },
  "overview.metric.etaUnavailable": {
    en: "ETA unavailable",
    zh: "暂时无法估计剩余时间",
    intent: "Fallback label when the run cannot estimate the remaining time.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime status band.",
  },
  "overview.metric.etaSecondsRemaining": {
    en: "{seconds}s remaining",
    zh: "还剩 {seconds} 秒",
    intent: "Compact ETA label for less than one minute remaining.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime status band.",
  },
  "overview.metric.etaMinutesSecondsRemaining": {
    en: "{minutes}m {seconds}s remaining",
    zh: "还剩 {minutes} 分 {seconds} 秒",
    intent: "Compact ETA label for less than one hour remaining with seconds detail.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime status band.",
  },
  "overview.metric.etaMinutesRemaining": {
    en: "{minutes}m remaining",
    zh: "还剩 {minutes} 分",
    intent: "Compact ETA label for less than one hour remaining.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime status band.",
  },
  "overview.metric.etaHoursMinutesRemaining": {
    en: "{hours}h {minutes}m remaining",
    zh: "还剩 {hours} 小时 {minutes} 分",
    intent: "Compact ETA label for multiple hours remaining with minute detail.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime status band.",
  },
  "overview.metric.etaHoursRemaining": {
    en: "{hours}h remaining",
    zh: "还剩 {hours} 小时",
    intent: "Compact ETA label for multiple hours remaining without minute detail.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime status band.",
  },
  "overview.section.interrupted": {
    en: "Interrupted",
    zh: "处理中断",
    intent: "Eyebrow label for failed or interrupted overview state.",
    toneNote: "Calm but serious.",
    usageScope: "Error book overview state.",
  },
  "overview.error.interruptedTitle": {
    en: "This reading run was interrupted",
    zh: "处理过程已中断",
    intent: "Error-state headline for interrupted reading runs.",
    toneNote: "Calm and factual.",
    usageScope: "Book overview error state.",
  },
  "overview.error.interruptedDescription": {
    en: "Realtime sync is unavailable for this book right now. Try again in a moment, or return to the shelf and reopen it.",
    zh: "这本书目前无法继续同步实时状态，请稍后重试或返回书架重新进入。",
    intent: "Error-state body copy for interrupted runs.",
    toneNote: "Actionable and calm.",
    usageScope: "Book overview error state.",
  },
  "overview.section.runConsole": {
    en: "Run Console",
    zh: "运行总控",
    intent: "Primary status console heading for in-progress runs.",
    toneNote: "Tool-like and clear.",
    usageScope: "Book overview runtime state band.",
  },
  "overview.metric.currentChapter": {
    en: "Current chapter",
    zh: "当前章节",
    intent: "Runtime metric label.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime state band.",
  },
  "overview.metric.currentStep": {
    en: "Current step",
    zh: "当前步骤",
    intent: "Runtime metric label while parsing.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime state band.",
  },
  "overview.metric.currentFocus": {
    en: "Current focus",
    zh: "当前焦点",
    intent: "Runtime metric label while reading.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime state band.",
  },
  "overview.metric.runtimeState": {
    en: "Current runtime state",
    zh: "当前运行状态",
    intent: "Runtime metric label for the top-level reading state.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime state band.",
  },
  "overview.runtime.reactionsSummary": {
    en: "{count} reactions surfaced in this chapter so far",
    zh: "本章当前已产出 {count} 条反应",
    intent: "Expandable reaction summary inside the runtime band.",
    toneNote: "Factual and live.",
    usageScope: "Book overview runtime state band.",
  },
  "overview.runtime.lastCheckpoint": {
    en: "Latest checkpoint: {value}",
    zh: "最新 checkpoint：{value}",
    intent: "Checkpoint timestamp line under the runtime band.",
    toneNote: "Tool-like, concise.",
    usageScope: "Book overview runtime state band.",
  },
  "overview.runtime.syncing": {
    en: "Syncing runtime state...",
    zh: "正在同步运行时状态...",
    intent: "Transient sync helper text.",
    toneNote: "Short and tool-like.",
    usageScope: "Book overview runtime state band and runtime panel.",
  },
  "overview.runtime.retry": {
    en: "Retry sync",
    zh: "重试同步",
    intent: "Retry action for runtime polling failures.",
    toneNote: "Short and direct.",
    usageScope: "Book overview runtime band and runtime panel.",
  },
  "overview.runtime.pending": {
    en: "Pending",
    zh: "等待中",
    intent: "Fallback runtime step label before a concrete phase exists.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime band.",
  },
  "overview.runtime.waitingForStructure": {
    en: "Waiting for structure",
    zh: "等待结构就绪",
    intent: "Fallback current chapter value before any chapter is ready.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime band.",
  },
  "overview.runtime.state.paused.label": {
    en: "Paused",
    zh: "已暂停",
    intent: "Runtime-state label when the reading run is paused.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.paused.detail": {
    en: "Deep reading is paused right now. You can resume it from here later.",
    zh: "当前深读流程已暂停，可以稍后从这里继续。",
    intent: "Runtime-state detail when the reading run is paused.",
    toneNote: "Calm and actionable.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.blocked.label": {
    en: "Reading is blocked",
    zh: "阅读被阻塞",
    intent: "Runtime-state label when reading is waiting for the next chapter to be prepared.",
    toneNote: "Clear and serious.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.blocked.detail": {
    en: "Deep reading will continue after the next chapter finishes segmentation.",
    zh: "等待下一章切分完成后继续深读。",
    intent: "Runtime-state detail when reading is blocked on segmentation.",
    toneNote: "Calm and explanatory.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.preparing.label": {
    en: "Preparing readable chapters",
    zh: "准备可读章节",
    intent: "Runtime-state label before the first chapter is segmented enough to read.",
    toneNote: "Clear and anticipatory.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.preparing.detail": {
    en: "Deep reading will start automatically once the first chapter is segmented.",
    zh: "首章语义切分完成后会自动开始深读。",
    intent: "Runtime-state detail before the first readable chapter is ready.",
    toneNote: "Calm and reassuring.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.segmenting.label": {
    en: "Segmenting",
    zh: "切分中",
    intent: "Runtime-state label while semantic segmentation is actively preparing future reading.",
    toneNote: "Short and tool-like.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.segmenting.detail": {
    en: "Preparing semantic structure for the next reading steps.",
    zh: "正在为后续阅读准备语义结构。",
    intent: "Fallback runtime-state detail while segmenting.",
    toneNote: "Tool-like and factual.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.reading.label": {
    en: "Reading",
    zh: "正在阅读",
    intent: "Runtime-state label while the reader is actively processing text.",
    toneNote: "Short and live.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.reading.detail": {
    en: "Advancing through the current chapter.",
    zh: "正在推进当前章节。",
    intent: "Fallback runtime-state detail while the reader is active.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.running.label": {
    en: "Deep reading in progress",
    zh: "深读进行中",
    intent: "Fallback runtime-state label when the run is active but not in a more specific sub-state.",
    toneNote: "Short and calm.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.running.detail": {
    en: "The current chapter is still moving forward.",
    zh: "正在推进当前章节的深读过程。",
    intent: "Fallback runtime-state detail for a generic active run.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.currentStep.prefix": {
    en: "Current step: {value}",
    zh: "当前步骤: {value}",
    intent: "Prefix template for chapter navigator and runtime labels that expose the current processing step.",
    toneNote: "Short and factual.",
    usageScope: "Book overview structure navigator.",
  },
  "overview.runtime.currentStep.preparing": {
    en: "Current step: Preparing readable structure",
    zh: "当前步骤: 正在准备可读结构",
    intent: "Fallback current-step label before a concrete parse step exists.",
    toneNote: "Short and factual.",
    usageScope: "Book overview structure navigator.",
  },
  "overview.runtime.currentStatus.prefix": {
    en: "Current state: {value}",
    zh: "当前状态: {value}",
    intent: "Prefix template for chapter navigator runtime context when the reader is active but not focused on a section ref.",
    toneNote: "Short and factual.",
    usageScope: "Book overview structure navigator.",
  },
  "overview.runtime.currentStatus.reading": {
    en: "Current state: Deep reading is active",
    zh: "当前状态: 正在深读",
    intent: "Fallback runtime state line for the current chapter navigator card.",
    toneNote: "Short and factual.",
    usageScope: "Book overview structure navigator.",
  },
  "overview.runtime.waitingResume": {
    en: "Waiting to resume reading",
    zh: "等待继续阅读",
    intent: "Status line shown when a completed current chapter is waiting for reading to continue.",
    toneNote: "Short and factual.",
    usageScope: "Book overview structure navigator.",
  },
  "overview.runtime.waitingNext": {
    en: "Waiting for the next chapter to finish segmentation",
    zh: "等待下一章切分完成",
    intent: "Status line shown when reading is blocked on the next chapter.",
    toneNote: "Short and factual.",
    usageScope: "Book overview structure navigator.",
  },
  "overview.runtime.readingSection": {
    en: "Reading: {value}",
    zh: "正在阅读: {value}",
    intent: "Status line for the current section inside the active chapter.",
    toneNote: "Short and live.",
    usageScope: "Book overview structure navigator.",
  },
  "overview.section.explore": {
    en: "Explore this book",
    zh: "探索这本书",
    intent: "Eyebrow label for the mode switch section.",
    toneNote: "Guide-like and calm.",
    usageScope: "Book overview mode switcher.",
  },
  "overview.structure.emptyNotReady": {
    en: "Book structure is not ready yet",
    zh: "书籍结构暂未准备好",
    intent: "Structure empty-state title before the outline exists.",
    toneNote: "Calm and factual.",
    usageScope: "Book overview structure area.",
  },
  "overview.structure.emptyNotReadyMessage": {
    en: "The book was added, but the parsed chapter structure is not available yet.",
    zh: "这本书已经加入书架，但解析后的章节结构暂时还不可用。",
    intent: "Structure empty-state body before the outline exists.",
    toneNote: "Calm and factual.",
    usageScope: "Book overview structure area.",
  },
  "overview.structure.emptyProgress": {
    en: "No chapters are available yet",
    zh: "还没有可显示的章节",
    intent: "Structure empty-state title while runtime views are still empty.",
    toneNote: "Calm and factual.",
    usageScope: "Book overview structure area.",
  },
  "overview.structure.emptyProgressMessage": {
    en: "Chapter-level structure will appear here as the parser and reader make progress.",
    zh: "随着解析和阅读推进，章节结构会显示在这里。",
    intent: "Structure empty-state body while runtime views are still empty.",
    toneNote: "Calm and forward-looking.",
    usageScope: "Book overview structure area.",
  },
  "overview.structure.openCompletedChapter": {
    en: "Open completed chapter",
    zh: "打开已完成章节",
    intent: "CTA hint for completed chapters in structure views.",
    toneNote: "Short and direct.",
    usageScope: "Book overview structure lists and runtime navigator.",
  },
  "overview.structure.expand": {
    en: "Expand",
    zh: "展开",
    intent: "Action label for collapsed mobile structure panel.",
    toneNote: "Short and direct.",
    usageScope: "Book overview mobile structure navigator.",
  },
  "overview.structure.mobileHint": {
    en: "Open completed chapters here and keep the live position in view.",
    zh: "从这里打开已完成章节，并保持当前进度在视野中。",
    intent: "Support copy for collapsed mobile structure panel.",
    toneNote: "Helpful and concise.",
    usageScope: "Book overview mobile structure navigator.",
  },
  "overview.structure.desktopHint": {
    en: "Open completed chapters first and keep the current position pinned.",
    zh: "优先从这里进入已完成章节，并持续追踪当前位置。",
    intent: "Support copy for desktop structure navigator.",
    toneNote: "Helpful and concise.",
    usageScope: "Book overview desktop structure navigator.",
  },
  "overview.marks.emptyTitle": {
    en: "No marks for this book yet",
    zh: "这本书还没有标记",
    intent: "Book-scoped marks empty-state title.",
    toneNote: "Calm and factual.",
    usageScope: "Book overview marks tab.",
  },
  "overview.marks.emptyMessage": {
    en: "Resonance, blindspot, and bookmark marks will appear here as soon as you save them from completed chapters.",
    zh: "当你在已完成章节里保存共鸣、盲点或书签标记后，它们会出现在这里。",
    intent: "Book-scoped marks empty-state body.",
    toneNote: "Helpful and forward-looking.",
    usageScope: "Book overview marks tab.",
  },
  "overview.mindstream.title": {
    en: "Reading mindstream",
    zh: "阅读心流",
    intent: "Main runtime narrative panel title.",
    toneNote: "Productive and evocative.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.empty": {
    en: "Waiting for the first visible thought.",
    zh: "等待第一条可见思路浮现。",
    intent: "Empty-state copy for visible mindstream events.",
    toneNote: "Quiet and minimal.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.live.reading.default": {
    en: "Reading the next line",
    zh: "正在读下一句",
    intent: "Default live-activity line while the reader is taking in the next sentence.",
    toneNote: "Clear, calm, and quietly alive.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.reading.alternate": {
    en: "Staying with a sentence",
    zh: "正在停留在这句话上",
    intent: "Alternate live-activity line while the reader remains with a sentence.",
    toneNote: "Clear, lyrical, and in-progress.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.thinking.default": {
    en: "Turning a line over",
    zh: "正在反复咂摸这句话",
    intent: "Generic live-activity line for active thinking before a clearer thought family emerges.",
    toneNote: "Clear, lyrical, and in-progress.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.thinking.discern": {
    en: "Turning a claim over",
    zh: "正在反复推敲一个说法",
    intent: "Live-activity line for a discern-style thinking phase.",
    toneNote: "Clear, incisive, and in-progress.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.thinking.association": {
    en: "Following a resonance",
    zh: "正在顺着一阵回响追下去",
    intent: "Live-activity line for an association-style thinking phase.",
    toneNote: "Clear, connective, and quietly alive.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.thinking.curious": {
    en: "Following a question",
    zh: "正在顺着一个问题走下去",
    intent: "Live-activity line for a curious thinking phase before search begins.",
    toneNote: "Clear, curious, and in-progress.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.thinking.retrospect": {
    en: "Returning to an earlier thread",
    zh: "正在回到前面的线索上",
    intent: "Live-activity line for a retrospect-style thinking phase.",
    toneNote: "Clear, reflective, and in-progress.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.thinking.highlight": {
    en: "Staying with a line",
    zh: "正在留住一句话",
    intent: "Live-activity line for a highlight-style thinking phase.",
    toneNote: "Clear, attentive, and in-progress.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.searching.default": {
    en: "Looking into a question",
    zh: "正在查一个问题",
    intent: "Default live-activity line while the reader is searching.",
    toneNote: "Clear, investigative, and in-progress.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.searching.curious": {
    en: "Pulling on a thread",
    zh: "正在顺着一条线索往下拉",
    intent: "Alternate live-activity line for curiosity-driven searching.",
    toneNote: "Clear, curious, and quietly alive.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.fusing.default": {
    en: "Working the thread further",
    zh: "正在把这条线索继续编下去",
    intent: "Default live-activity line while the reader fuses new material into the current thought.",
    toneNote: "Clear, connective, and in-progress.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.fusing.alternate": {
    en: "Bringing the pieces together",
    zh: "正在把零散的东西接起来",
    intent: "Alternate live-activity line while the reader integrates search/context back into the thought.",
    toneNote: "Clear, connective, and quietly active.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.reflecting.default": {
    en: "Checking what holds",
    zh: "正在看什么还能站得住",
    intent: "Default live-activity line while the reader reflects on a thought.",
    toneNote: "Clear, reflective, and in-progress.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.reflecting.alternate": {
    en: "Seeing what survives",
    zh: "正在看最后留下了什么",
    intent: "Alternate live-activity line while the reader tests what remains after reflection.",
    toneNote: "Clear, reflective, and quietly alive.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.waiting.default": {
    en: "Waiting for the next chapter",
    zh: "正在等待下一章准备好",
    intent: "Live-activity line when the reader is blocked waiting for preparation work.",
    toneNote: "Clear and patient.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.preparing.default": {
    en: "Preparing the next chapter",
    zh: "正在准备下一章",
    intent: "Live-activity line when the reader is still preparing readable structure.",
    toneNote: "Clear and patient.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.moreThoughts": {
    en: "+{count} more thoughts",
    zh: "+{count} 条延伸思路",
    intent: "Expand control for additional reactions attached to one sentence-level moment.",
    toneNote: "Light and literary.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.hideExtraThoughts": {
    en: "Hide extra thoughts",
    zh: "收起延伸思路",
    intent: "Collapse control for additional reactions attached to one sentence-level moment.",
    toneNote: "Light and calm.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.openInChapterTooltip": {
    en: "Open the chapter workspace",
    zh: "打开章节工作区",
    intent: "Tooltip and aria label for the icon-only jump from one mindstream moment into a completed chapter.",
    toneNote: "Quiet and actionable.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.openInChapter": {
    en: "Open in chapter",
    zh: "在章节中查看",
    intent: "Secondary link from one mindstream moment into the completed chapter result.",
    toneNote: "Quiet and actionable.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.trace.discern.default": {
    en: "A claim drew pressure",
    zh: "一个说法承受了推敲",
    intent: "Historical label for a discern reaction once it has moved out of the current thread.",
    toneNote: "Quiet, reflective, and complete.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.trace.discern.question": {
    en: "A question opened",
    zh: "一个问题被打开了",
    intent: "Historical label for a discern reaction framed as an opened question.",
    toneNote: "Quiet, reflective, and complete.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.trace.association.default": {
    en: "A connection surfaced",
    zh: "一条连接浮现了出来",
    intent: "Historical label for an association reaction once it has moved into the trace rail.",
    toneNote: "Quiet and literary.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.trace.association.echo": {
    en: "An echo appeared",
    zh: "一道回响浮现了",
    intent: "Historical label for an association reaction that echoes earlier pages.",
    toneNote: "Quiet and literary.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.trace.curious.default": {
    en: "A thread opened",
    zh: "一条线索被打开了",
    intent: "Historical label for a curious reaction after it moves into the trace rail.",
    toneNote: "Light, active, and complete.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.trace.curious.search": {
    en: "A question kept pulling",
    zh: "一个问题一直牵着它",
    intent: "Historical label for a curious reaction that triggered a search.",
    toneNote: "Light, active, and complete.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.trace.retrospect.default": {
    en: "An earlier thread returned",
    zh: "前面的线索又回来了",
    intent: "Historical label for a retrospect reaction after it moves into the trace rail.",
    toneNote: "Quiet and reflective.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.trace.retrospect.echo": {
    en: "Something from before resurfaced",
    zh: "前面的东西又浮了上来",
    intent: "Historical label for a retrospect reaction that clearly recalls an earlier line.",
    toneNote: "Quiet and reflective.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.trace.highlight.default": {
    en: "A line stayed with it",
    zh: "一句话留在了心里",
    intent: "Historical label for a highlight-only moment in the trace rail.",
    toneNote: "Quiet and attentive.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.programLog.title": {
    en: "Program log ({count})",
    zh: "程序日志（{count}）",
    intent: "Summary label for the raw system-event log.",
    toneNote: "Tool-like and factual.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.programLog.description": {
    en: "Parsing, checkpoints, waiting, and resume events stay here so they don't interrupt the reading mindstream.",
    zh: "这里收纳解析、checkpoint、等待与恢复事件，默认不打断阅读心流。",
    intent: "Description for the raw system-event log.",
    toneNote: "Clear and factual.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.programLog.empty": {
    en: "No system-side events yet.",
    zh: "还没有系统侧事件。",
    intent: "Empty-state copy for the program log.",
    toneNote: "Brief and factual.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.technicalLog.title": {
    en: "Technical log",
    zh: "技术日志",
    intent: "Heading for the low-level runtime output panel.",
    toneNote: "Tool-like.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.technicalLog.show": {
    en: "Show recent runtime output",
    zh: "查看最近运行输出",
    intent: "Disclosure label for raw runtime output.",
    toneNote: "Direct and tool-like.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.technicalLog.empty": {
    en: "Runtime output will appear here as the parser or reader writes new lines.",
    zh: "当解析器或阅读器写入新日志时，运行输出会显示在这里。",
    intent: "Empty-state copy for the technical log.",
    toneNote: "Tool-like and factual.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.syncError.default": {
    en: "Realtime state is temporarily unavailable.",
    zh: "实时状态暂时不可用。",
    intent: "Fallback runtime sync error body.",
    toneNote: "Calm and factual.",
    usageScope: "Book overview runtime panel.",
  },
  "system.stage.queued": {
    en: "Queued",
    zh: "等待开始",
    intent: "Structured top-status label for queued jobs.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.stage.parsingStructure": {
    en: "Parsing book structure",
    zh: "正在解析书籍结构",
    intent: "Structured top-status label while the base book structure is being prepared.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.stage.parsingChapter": {
    en: "Parsing {chapter}",
    zh: "正在解析 {chapter}",
    intent: "Structured top-status label while parsing a specific chapter into readable structure.",
    toneNote: "Short and live.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.stage.ready": {
    en: "Structure is ready",
    zh: "结构已就绪",
    intent: "Structured top-status label when the base structure has been parsed.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.stage.deepReadingChapter": {
    en: "Reading {chapter}",
    zh: "正在分析 {chapter}",
    intent: "Structured top-status label while deep reading a specific chapter.",
    toneNote: "Short and live.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.stage.deepReading": {
    en: "Deep reading in progress",
    zh: "正在顺序深读",
    intent: "Structured top-status label while deep reading without a specific chapter ref.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.stage.chapterNoteGeneration": {
    en: "Writing chapter notes",
    zh: "正在生成章节笔记",
    intent: "Structured top-status label while generating chapter notes.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.stage.paused": {
    en: "Paused, ready to resume",
    zh: "已暂停，可继续",
    intent: "Structured top-status label for a paused reading run.",
    toneNote: "Short and actionable.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.stage.completed": {
    en: "Completed",
    zh: "全部完成",
    intent: "Structured top-status label for a completed reading run.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.stage.error": {
    en: "Interrupted",
    zh: "分析中断",
    intent: "Structured top-status label for interrupted runs.",
    toneNote: "Short and serious.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.step.waitingToResume": {
    en: "Waiting to resume",
    zh: "等待继续执行",
    intent: "Structured runtime-step label for paused runs awaiting resume.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.step.prepareChapterStructure": {
    en: "Preparing chapter structure",
    zh: "准备章节结构",
    intent: "Structured runtime-step label before semantic segmentation builds chapter structure.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.step.segmenting": {
    en: "Segmenting semantically",
    zh: "语义切分中",
    intent: "Structured runtime-step label during semantic segmentation.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.step.structureCheckpointSaved": {
    en: "Structure checkpoint saved",
    zh: "已保存结构 checkpoint",
    intent: "Structured runtime-step label after a structure checkpoint is written.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.step.structureParseFailed": {
    en: "Structure parsing failed",
    zh: "结构解析失败",
    intent: "Structured runtime-step label for parse failure.",
    toneNote: "Short and serious.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.step.waitingCurrentChapterSegmentation": {
    en: "Waiting for the current chapter to finish segmentation",
    zh: "等待当前章节切分完成",
    intent: "Structured runtime-step label while the reader waits on the current chapter segmentation.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.step.prefetchFutureChapters": {
    en: "Preparing future chapters in the background",
    zh: "后台准备后续章节",
    intent: "Structured runtime-step label while background segmentation prefetches later chapters.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.step.prepareFirstChapter": {
    en: "Preparing the first readable chapter",
    zh: "为首章准备语义结构",
    intent: "Structured runtime-step label before the first chapter is ready to read.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.step.waitingFirstChapterSegmentation": {
    en: "Waiting for the first chapter to finish segmentation",
    zh: "等待首章切分",
    intent: "Structured runtime-step label while waiting for the first chapter to become readable.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.step.waitingNextChapterSegmentation": {
    en: "Waiting for the next chapter to finish segmentation",
    zh: "等待后续章节切分",
    intent: "Structured runtime-step label while waiting for a future chapter to become readable.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "chapter.tooltip.prevChapter": {
    en: "Previous chapter",
    zh: "上一章",
    intent: "Tooltip for previous-chapter navigation.",
    toneNote: "Purely functional.",
    usageScope: "Chapter reading toolbar.",
  },
  "chapter.tooltip.nextChapter": {
    en: "Next chapter",
    zh: "下一章",
    intent: "Tooltip for next-chapter navigation.",
    toneNote: "Purely functional.",
    usageScope: "Chapter reading toolbar.",
  },
  "chapter.tooltip.prevSection": {
    en: "Previous section",
    zh: "上一段",
    intent: "Tooltip for previous-section navigation.",
    toneNote: "Purely functional.",
    usageScope: "Chapter reading toolbar.",
  },
  "chapter.tooltip.nextSection": {
    en: "Next section",
    zh: "下一段",
    intent: "Tooltip for next-section navigation.",
    toneNote: "Purely functional.",
    usageScope: "Chapter reading toolbar.",
  },
  "chapter.loading": {
    en: "Loading chapter workspace...",
    zh: "正在加载章节工作区...",
    intent: "Loading title for the chapter reading workspace.",
    toneNote: "Neutral and functional.",
    usageScope: "Chapter reading loading state.",
  },
  "chapter.error.title": {
    en: "Chapter workspace is unavailable",
    zh: "章节工作区暂时不可用",
    intent: "Error title when the chapter reading workspace cannot load.",
    toneNote: "Calm and informative.",
    usageScope: "Chapter reading error state.",
  },
  "chapter.error.message": {
    en: "We could not load this chapter right now.",
    zh: "当前无法加载这个章节。",
    intent: "Error body copy when the chapter reading workspace cannot load.",
    toneNote: "Calm and informative.",
    usageScope: "Chapter reading error state.",
  },
  "chapter.error.backToBooks": {
    en: "Back to books",
    zh: "返回书架",
    intent: "Recovery link from chapter reading errors back to the bookshelf.",
    toneNote: "Short and directional.",
    usageScope: "Chapter reading error state.",
  },
  "chapter.filter.all": {
    en: "All",
    zh: "全部",
    intent: "Filter label that shows every reaction type.",
    toneNote: "Short and utilitarian.",
    usageScope: "Chapter reading filter rail.",
  },
  "chapter.reader.originalBookFallback": {
    en: "Original book",
    zh: "原书",
    intent: "Fallback title when the original book title is missing in the reader workspace.",
    toneNote: "Neutral and descriptive.",
    usageScope: "Chapter reading workspace and source reader.",
  },
  "chapter.reader.bookProgress": {
    en: "Book {value}",
    zh: "全书 {value}",
    intent: "Compact book-level reading progress badge in the chapter toolbar.",
    toneNote: "Short and factual.",
    usageScope: "Chapter reading toolbar.",
  },
  "chapter.reader.bookProgressUnavailable": {
    en: "Book progress pending",
    zh: "全书进度待更新",
    intent: "Fallback label when book-level progress is not yet available.",
    toneNote: "Calm and factual.",
    usageScope: "Chapter reading toolbar.",
  },
  "chapter.reader.settingsAria": {
    en: "Reading settings",
    zh: "阅读设置",
    intent: "Accessible label for the chapter reading settings trigger.",
    toneNote: "Purely functional.",
    usageScope: "Chapter reading toolbar.",
  },
  "chapter.reader.settingsTitle": {
    en: "Reading text size",
    zh: "阅读文字大小",
    intent: "Title for the chapter reading settings popover.",
    toneNote: "Short and functional.",
    usageScope: "Chapter reading settings popover.",
  },
  "chapter.reader.settingsDescription": {
    en: "Applies to both reactions and the original book.",
    zh: "同时应用于反应侧和原书侧。",
    intent: "Supporting description for the reading settings popover.",
    toneNote: "Helpful and concise.",
    usageScope: "Chapter reading settings popover.",
  },
  "chapter.reader.tabReactions": {
    en: "Reactions",
    zh: "反应",
    intent: "Tab label for the reactions panel in mobile chapter reading.",
    toneNote: "Short and utilitarian.",
    usageScope: "Chapter reading mobile tabs.",
  },
  "chapter.reader.tabOriginalBook": {
    en: "Original book",
    zh: "原书",
    intent: "Tab label for the source reader panel in mobile chapter reading.",
    toneNote: "Short and utilitarian.",
    usageScope: "Chapter reading mobile tabs.",
  },
  "chapter.reader.loadingSource": {
    en: "Loading source EPUB...",
    zh: "正在加载原始 EPUB...",
    intent: "Loading text shown while the source reader initializes.",
    toneNote: "Functional and calm.",
    usageScope: "Source reader pane.",
  },
  "chapter.sheet.backToChapters": {
    en: "Chapters",
    zh: "章节",
    intent: "Back action in the mobile chapter sheet from section preview to chapter list.",
    toneNote: "Short and directional.",
    usageScope: "Chapter sheet mobile navigation.",
  },
  "chapter.sheet.status.current": {
    en: "Current",
    zh: "当前",
    intent: "Status label for the chapter currently open in the reading workspace.",
    toneNote: "Short and factual.",
    usageScope: "Chapter sheet chapter list.",
  },
  "chapter.sheet.status.pending": {
    en: "Pending",
    zh: "待完成",
    intent: "Status label for a chapter whose result is not ready yet.",
    toneNote: "Short and factual.",
    usageScope: "Chapter sheet chapter list.",
  },
  "chapter.sheet.status.error": {
    en: "Error",
    zh: "出错",
    intent: "Status label for a chapter whose result failed to prepare.",
    toneNote: "Short and serious.",
    usageScope: "Chapter sheet chapter list.",
  },
  "chapter.sheet.status.completed": {
    en: "Completed",
    zh: "已完成",
    intent: "Status label for a chapter whose result is ready to open.",
    toneNote: "Short and factual.",
    usageScope: "Chapter sheet chapter list.",
  },
  "chapter.sheet.structureBadge": {
    en: "Structure",
    zh: "结构",
    intent: "Small badge indicating a heading block inside the chapter outline.",
    toneNote: "Short and descriptive.",
    usageScope: "Chapter sheet outline heading block.",
  },
  "chapter.sheet.emptySections": {
    en: "No semantic sections available.",
    zh: "还没有可用的语义段落。",
    intent: "Empty-state text when a chapter outline has no semantic sections.",
    toneNote: "Calm and factual.",
    usageScope: "Chapter sheet section previews.",
  },
  "chapter.sheet.inThisChapter": {
    en: "In this chapter",
    zh: "本章结构",
    intent: "Eyebrow label for the chapter outline preview column.",
    toneNote: "Short and descriptive.",
    usageScope: "Chapter sheet desktop preview panel.",
  },
  "chapter.sheet.previewFallback": {
    en: "Chapter preview",
    zh: "章节预览",
    intent: "Fallback title for the chapter outline preview panel.",
    toneNote: "Neutral and descriptive.",
    usageScope: "Chapter sheet desktop preview panel.",
  },
  "chapter.sheet.loadingOutline": {
    en: "Loading chapter outline...",
    zh: "正在加载章节结构...",
    intent: "Loading copy while the chapter outline preview is fetched.",
    toneNote: "Neutral and functional.",
    usageScope: "Chapter sheet desktop preview panel.",
  },
  "chapter.sheet.notReadyTitle": {
    en: "This chapter is not ready yet.",
    zh: "这个章节暂时还不可用。",
    intent: "Headline when a chapter result is not ready for section-level navigation.",
    toneNote: "Calm and factual.",
    usageScope: "Chapter sheet desktop preview panel.",
  },
  "chapter.sheet.notReadyMessage": {
    en: "Finish analysis in the book overview before using section-level navigation here.",
    zh: "请先在书籍总览中完成分析，再来这里使用段落级导航。",
    intent: "Supporting text when a chapter result is not ready for section-level navigation.",
    toneNote: "Helpful and directive.",
    usageScope: "Chapter sheet desktop preview panel.",
  },
} as const satisfies Record<string, ControlledCopyEntry>;

export type ControlledCopyKey = keyof typeof CONTROLLED_COPY;

export function copy(key: ControlledCopyKey, params?: Record<string, string | number | null | undefined>): string {
  return formatTemplate(resolveLocalizedText(CONTROLLED_COPY[key], APP_LOCALE), params);
}

export function copyForLocale(
  key: ControlledCopyKey,
  locale: AppLocale,
  params?: Record<string, string | number | null | undefined>,
): string {
  return formatTemplate(resolveLocalizedText(CONTROLLED_COPY[key], locale), params);
}

export function maybeCopy(
  key: string | null | undefined,
  params?: Record<string, string | number | null | undefined>,
): string | null {
  if (!key || !(key in CONTROLLED_COPY)) {
    return null;
  }
  return copy(key as ControlledCopyKey, params);
}

export function localizedText(text: LocalizedText): string {
  return resolveLocalizedText(text, APP_LOCALE);
}
