import { APP_LOCALE, formatTemplate, resolveLocalizedText, type AppLocale, type LocalizedText } from "./app-locale";

type ControlledCopyEntry = {
  en: string;
  zh: string;
  intent: string;
  toneNote: string;
  usageScope: string;
};

export const CONTROLLED_COPY = {
  "page.books.title": {
    en: "Books",
    zh: "书架",
    intent: "Page title for the main bookshelf view.",
    toneNote: "Plain, utilitarian, neutral.",
    usageScope: "Document titles and bookshelf header.",
  },
  "page.marks.title": {
    en: "My Marks",
    zh: "我的标记",
    intent: "Page title for the workspace marks view.",
    toneNote: "Plain, utilitarian, neutral.",
    usageScope: "Document titles and marks page header.",
  },
  "page.upload.title": {
    en: "Upload",
    zh: "上传",
    intent: "Page title for upload-related routes.",
    toneNote: "Short and functional.",
    usageScope: "Document titles.",
  },
  "page.analysis.title": {
    en: "Reading in progress",
    zh: "分析中",
    intent: "Page title for legacy analysis routes redirecting to active reading.",
    toneNote: "Short and stateful.",
    usageScope: "Document titles.",
  },
  "analysis.loading": {
    en: "Loading reading progress...",
    zh: "正在加载阅读进度...",
    intent: "Compatibility analysis page loading title.",
    toneNote: "Neutral and functional.",
    usageScope: "Compatibility analysis page loading state.",
  },
  "analysis.error.title": {
    en: "Reading status is unavailable",
    zh: "阅读状态暂时不可用",
    intent: "Compatibility analysis page error title.",
    toneNote: "Calm and informative.",
    usageScope: "Compatibility analysis page error state.",
  },
  "analysis.error.message": {
    en: "The reading progress is not available right now.",
    zh: "当前无法获取阅读进度。",
    intent: "Compatibility analysis page error message.",
    toneNote: "Calm and informative.",
    usageScope: "Compatibility analysis page error state.",
  },
  "analysis.action.backToBooks": {
    en: "Back to books",
    zh: "返回书架",
    intent: "Compatibility analysis page recovery link.",
    toneNote: "Short and direct.",
    usageScope: "Compatibility analysis page error state.",
  },
  "analysis.eyebrow.live": {
    en: "Reading status",
    zh: "阅读状态",
    intent: "Top eyebrow for live compatibility analysis page states.",
    toneNote: "Neutral and product-like.",
    usageScope: "Compatibility analysis page header.",
  },
  "analysis.eyebrow.lastKnown": {
    en: "Last known reading state",
    zh: "上次已知的阅读状态",
    intent: "Top eyebrow for paused last-known compatibility analysis page states.",
    toneNote: "Honest and non-live.",
    usageScope: "Compatibility analysis page header.",
  },
  "analysis.action.openCurrent": {
    en: "Open current page",
    zh: "打开当前页面",
    intent: "Primary action from the compatibility analysis page into the current routed surface.",
    toneNote: "Short and direct.",
    usageScope: "Compatibility analysis page header.",
  },
  "analysis.meta.etaUnavailable": {
    en: "ETA unavailable",
    zh: "暂时无法估计剩余时间",
    intent: "Fallback ETA text on the compatibility analysis page.",
    toneNote: "Short and factual.",
    usageScope: "Compatibility analysis page header metrics.",
  },
  "analysis.meta.lastCheckpoint": {
    en: "Last checkpoint: {value}",
    zh: "最近 checkpoint：{value}",
    intent: "Header metric showing the latest durable checkpoint for paused runs.",
    toneNote: "Short and factual.",
    usageScope: "Compatibility analysis page header metrics.",
  },
  "analysis.meta.noCheckpoint": {
    en: "No resumable checkpoint",
    zh: "没有可续读 checkpoint",
    intent: "Header metric when a paused run has no resumable checkpoint.",
    toneNote: "Honest and factual.",
    usageScope: "Compatibility analysis page header metrics.",
  },
  "analysis.meta.chapters": {
    en: "{completed}/{total} chapters",
    zh: "{completed}/{total} 章",
    intent: "Compact chapter progress metric on the compatibility analysis page.",
    toneNote: "Short and factual.",
    usageScope: "Compatibility analysis page header metrics.",
  },
  "analysis.section.structure": {
    en: "Structure",
    zh: "结构",
    intent: "Structure section title on the compatibility analysis page.",
    toneNote: "Short and factual.",
    usageScope: "Compatibility analysis page.",
  },
  "analysis.structure.status.ready": {
    en: "Ready",
    zh: "可查看",
    intent: "Compatibility analysis page structure status for completed chapters.",
    toneNote: "Short and factual.",
    usageScope: "Compatibility analysis page structure list.",
  },
  "analysis.structure.status.readingNow": {
    en: "Reading now",
    zh: "正在阅读",
    intent: "Compatibility analysis page structure status for the active chapter.",
    toneNote: "Short and live.",
    usageScope: "Compatibility analysis page structure list.",
  },
  "analysis.structure.status.pausedHere": {
    en: "Last stopped here",
    zh: "上次停在这里",
    intent: "Compatibility analysis page structure status for a paused chapter that reflects a last-known stop.",
    toneNote: "Short and non-live.",
    usageScope: "Compatibility analysis page structure list.",
  },
  "analysis.structure.status.needsAttention": {
    en: "Needs attention",
    zh: "需要处理",
    intent: "Compatibility analysis page structure status for chapter errors.",
    toneNote: "Short and serious.",
    usageScope: "Compatibility analysis page structure list.",
  },
  "analysis.structure.status.queued": {
    en: "Queued",
    zh: "排队中",
    intent: "Compatibility analysis page structure status for queued chapters.",
    toneNote: "Short and factual.",
    usageScope: "Compatibility analysis page structure list.",
  },
  "analysis.structure.openChapter": {
    en: "Open chapter result",
    zh: "打开章节结果",
    intent: "CTA into a finished chapter from the compatibility analysis page.",
    toneNote: "Short and direct.",
    usageScope: "Compatibility analysis page structure list.",
  },
  "analysis.section.currentState": {
    en: "Current state",
    zh: "当前状态",
    intent: "Current-state section title on the compatibility analysis page.",
    toneNote: "Short and factual.",
    usageScope: "Compatibility analysis page.",
  },
  "analysis.currentState.chapter": {
    en: "Chapter",
    zh: "章节",
    intent: "Current-state chapter label on the compatibility analysis page.",
    toneNote: "Short and factual.",
    usageScope: "Compatibility analysis page current state.",
  },
  "analysis.currentState.lastKnownChapter": {
    en: "Last chapter",
    zh: "上次章节",
    intent: "Current-state chapter label when the page shows a paused last-known stop.",
    toneNote: "Short and non-live.",
    usageScope: "Compatibility analysis page current state.",
  },
  "analysis.currentState.waitingForStructure": {
    en: "Waiting for structure",
    zh: "等待结构就绪",
    intent: "Fallback chapter value before any chapter is available.",
    toneNote: "Short and factual.",
    usageScope: "Compatibility analysis page current state.",
  },
  "analysis.currentState.section": {
    en: "Section",
    zh: "小节",
    intent: "Current-state section label on the compatibility analysis page.",
    toneNote: "Short and factual.",
    usageScope: "Compatibility analysis page current state.",
  },
  "analysis.currentState.lastKnownSection": {
    en: "Last section",
    zh: "上次小节",
    intent: "Current-state section label when the page shows a paused last-known stop.",
    toneNote: "Short and non-live.",
    usageScope: "Compatibility analysis page current state.",
  },
  "analysis.currentState.pending": {
    en: "Pending",
    zh: "等待中",
    intent: "Fallback section value on the compatibility analysis page.",
    toneNote: "Short and factual.",
    usageScope: "Compatibility analysis page current state.",
  },
  "analysis.currentState.noLivePulse": {
    en: "No live pulse yet.",
    zh: "还没有实时脉冲。",
    intent: "Fallback pulse message for active runs without a pulse.",
    toneNote: "Calm and factual.",
    usageScope: "Compatibility analysis page current state.",
  },
  "analysis.currentState.noLastKnownPulse": {
    en: "No last-known pulse is available for this paused run.",
    zh: "这次暂停运行没有可显示的上次脉冲。",
    intent: "Fallback pulse message for paused last-known runs.",
    toneNote: "Honest and calm.",
    usageScope: "Compatibility analysis page current state.",
  },
  "analysis.section.recentCompleted": {
    en: "Recently completed",
    zh: "最近完成",
    intent: "Recently completed section title on the compatibility analysis page.",
    toneNote: "Short and factual.",
    usageScope: "Compatibility analysis page.",
  },
  "analysis.section.activityFeed": {
    en: "Activity feed",
    zh: "活动流",
    intent: "Activity feed section title on the compatibility analysis page.",
    toneNote: "Short and factual.",
    usageScope: "Compatibility analysis page.",
  },
  "page.book.title": {
    en: "Book overview",
    zh: "书籍详情",
    intent: "Page title for the canonical book overview page.",
    toneNote: "Short and descriptive.",
    usageScope: "Document titles and page-level references.",
  },
  "page.chapter.title": {
    en: "Chapter reading",
    zh: "章节深读",
    intent: "Page title for the chapter reading workspace.",
    toneNote: "Short and descriptive.",
    usageScope: "Document titles.",
  },
  "layout.tagline": {
    en: "Deep reading workspace",
    zh: "深读工作台",
    intent: "Short brand-supporting tagline shown under the product name on the landing page.",
    toneNote: "Concise, quiet, product-like.",
    usageScope: "Top navigation brand area on the landing page.",
  },
  "state.loading.generic": {
    en: "Loading...",
    zh: "加载中...",
    intent: "Generic loading state fallback.",
    toneNote: "Brief and neutral.",
    usageScope: "Shared page-state loading card.",
  },
  "state.error.title": {
    en: "Unable to load this page",
    zh: "页面暂时无法加载",
    intent: "Generic error-state headline.",
    toneNote: "Calm and non-alarming.",
    usageScope: "Shared page-state error card.",
  },
  "state.error.backendUnavailable.title": {
    en: "Backend is unavailable",
    zh: "后端服务暂时不可用",
    intent: "Shared headline when the API cannot be reached at all.",
    toneNote: "Direct, calm, and diagnostic.",
    usageScope: "Primary page-level failures caused by the backend being offline.",
  },
  "state.error.backendUnavailable.message": {
    en: "The reading service looks offline. Retry after it reconnects.",
    zh: "阅读服务似乎已离线。待它重新连接后再试。",
    intent: "Shared explanatory copy when the API host is unreachable.",
    toneNote: "Plain and reassuring.",
    usageScope: "Primary page-level failures caused by the backend being offline.",
  },
  "action.retry": {
    en: "Retry",
    zh: "重试",
    intent: "Retry action for recoverable failures.",
    toneNote: "Direct and action-oriented.",
    usageScope: "Shared error and sync controls.",
  },
  "bookshelf.error.title": {
    en: "Bookshelf is unavailable",
    zh: "书架暂时不可用",
    intent: "Bookshelf page load failure headline.",
    toneNote: "Calm and informative.",
    usageScope: "Bookshelf error state.",
  },
  "bookshelf.error.message": {
    en: "We could not load your books right now.",
    zh: "当前无法加载你的书架内容。",
    intent: "Bookshelf page load failure body copy.",
    toneNote: "Calm and informative.",
    usageScope: "Bookshelf error state.",
  },
  "bookshelf.empty.title": {
    en: "No books yet",
    zh: "还没有书",
    intent: "Empty bookshelf headline.",
    toneNote: "Encouraging and concise.",
    usageScope: "Bookshelf empty state.",
  },
  "bookshelf.empty.message": {
    en: "Upload an EPUB to add the first book to this workspace.",
    zh: "上传一本 EPUB，把第一本书加入这个工作台。",
    intent: "Empty bookshelf body copy.",
    toneNote: "Inviting and concise.",
    usageScope: "Bookshelf empty state.",
  },
  "bookshelf.count.summary": {
    en: "{books} books · {marks} total marks",
    zh: "{books} 本书 · {marks} 个标记",
    intent: "Shelf-level summary under the main page title.",
    toneNote: "Compact and factual.",
    usageScope: "Bookshelf header.",
  },
  "bookshelf.action.addBook": {
    en: "Add book",
    zh: "添加新书",
    intent: "Primary action to open the upload flow.",
    toneNote: "Short CTA.",
    usageScope: "Bookshelf and empty-state primary action.",
  },
  "bookshelf.action.openMarks": {
    en: "My marks",
    zh: "我的标记",
    intent: "Secondary header action leading to marks.",
    toneNote: "Short navigation CTA.",
    usageScope: "Bookshelf header.",
  },
  "bookshelf.status.paused.runtimeStale": {
    en: "Paused after the reading state went stale",
    zh: "阅读状态过期后已暂停",
    intent: "Bookshelf summary for paused books whose runtime heartbeat went stale.",
    toneNote: "Calm, factual, and non-live.",
    usageScope: "Bookshelf card status summary.",
  },
  "bookshelf.status.paused.runtimeInterrupted": {
    en: "Paused after the reading run was interrupted",
    zh: "阅读中断后已暂停",
    intent: "Bookshelf summary for paused books whose runtime was interrupted.",
    toneNote: "Calm, factual, and non-live.",
    usageScope: "Bookshelf card status summary.",
  },
  "bookshelf.status.paused.resumeIncompatible": {
    en: "Paused, but this run cannot resume from here",
    zh: "已暂停，但当前无法从这里继续",
    intent: "Bookshelf summary for paused books whose saved run is not compatible with resume.",
    toneNote: "Honest and calm.",
    usageScope: "Bookshelf card status summary.",
  },
  "bookshelf.status.paused.devRunAbandoned": {
    en: "Paused after an abandoned development run",
    zh: "开发运行已放弃，当前处于暂停",
    intent: "Bookshelf summary for paused books left behind by a development-only run.",
    toneNote: "Honest and calm.",
    usageScope: "Bookshelf card status summary.",
  },
  "bookshelf.upload.title": {
    en: "Add a new book",
    zh: "添加一本新书",
    intent: "Upload dialog title from the bookshelf.",
    toneNote: "Direct and neutral.",
    usageScope: "Bookshelf upload dialog.",
  },
  "bookshelf.upload.description": {
    en: "Upload an EPUB and 书虫 will parse the book structure so deep reading can begin whenever you're ready.",
    zh: "上传 EPUB 文件，书虫会解析全书结构，准备好后可以随时开始深读。",
    intent: "Upload dialog explanatory copy.",
    toneNote: "Warm but concise.",
    usageScope: "Bookshelf upload dialog.",
  },
  "bookshelf.confirmation.title": {
    en: "“{title}” is now on your shelf",
    zh: "《{title}》已添加到书架",
    intent: "Deferred upload success dialog title.",
    toneNote: "Pleasant and clear.",
    usageScope: "Bookshelf deferred-upload confirmation dialog.",
  },
  "bookshelf.confirmation.description": {
    en: "The original chapter outline is ready with {count} chapters. Start deep reading now, or just return to the shelf for later.",
    zh: "原书目录已解析完成，共 {count} 章。要现在开始深读，还是先只进入书架？",
    intent: "Deferred upload success dialog explanation.",
    toneNote: "Clear choice framing.",
    usageScope: "Bookshelf deferred-upload confirmation dialog.",
  },
  "bookshelf.confirmation.later": {
    en: "Return to shelf",
    zh: "只进入书架",
    intent: "Deferred upload choice to postpone reading.",
    toneNote: "Quiet secondary action.",
    usageScope: "Bookshelf deferred-upload confirmation dialog.",
  },
  "bookshelf.confirmation.start": {
    en: "Start deep reading",
    zh: "开始深读",
    intent: "Deferred upload choice to start reading immediately.",
    toneNote: "Primary action, confident but not hype.",
    usageScope: "Bookshelf deferred-upload confirmation dialog and overview CTA.",
  },
  "upload.dialog.close": {
    en: "Close upload dialog",
    zh: "关闭上传对话框",
    intent: "Accessible label for the upload dialog close button.",
    toneNote: "Purely functional.",
    usageScope: "Upload dialog aria-label.",
  },
  "upload.dialog.drop": {
    en: "Drag & drop your EPUB here",
    zh: "将 EPUB 拖放到这里",
    intent: "Primary dropzone prompt.",
    toneNote: "Clear and inviting.",
    usageScope: "Upload dialog dropzone.",
  },
  "upload.dialog.dropActive": {
    en: "Drop your file here",
    zh: "把文件放在这里",
    intent: "Dropzone prompt while dragging.",
    toneNote: "Immediate and direct.",
    usageScope: "Upload dialog dropzone.",
  },
  "upload.dialog.release": {
    en: "Release to upload",
    zh: "松手即可上传",
    intent: "Dropzone secondary prompt while dragging.",
    toneNote: "Short and immediate.",
    usageScope: "Upload dialog dropzone.",
  },
  "upload.dialog.browse": {
    en: "browse files",
    zh: "浏览文件",
    intent: "Secondary inline action in the upload dropzone.",
    toneNote: "Short and lightweight.",
    usageScope: "Upload dialog dropzone.",
  },
  "upload.dialog.supports": {
    en: "Supports .epub format",
    zh: "支持 .epub 格式",
    intent: "Upload format support hint.",
    toneNote: "Informational.",
    usageScope: "Upload dialog footer.",
  },
  "upload.status.uploading": {
    en: "Uploading EPUB...",
    zh: "正在上传 EPUB...",
    intent: "Progress text while the file upload is in flight.",
    toneNote: "Purely functional.",
    usageScope: "Upload action status text.",
  },
  "upload.status.preparing": {
    en: "Preparing for deep reading...",
    zh: "正在准备深读流程...",
    intent: "Progress text after immediate upload is accepted.",
    toneNote: "Functional and anticipatory.",
    usageScope: "Upload action status text.",
  },
  "upload.status.parsingOutline": {
    en: "Parsing chapter outline...",
    zh: "正在解析章节目录...",
    intent: "Deferred upload outline preparation status.",
    toneNote: "Functional and concise.",
    usageScope: "Upload action status text.",
  },
  "upload.status.starting": {
    en: "Starting deep reading...",
    zh: "正在开始深读...",
    intent: "Progress text when confirming immediate start after upload.",
    toneNote: "Functional and concise.",
    usageScope: "Upload action status text.",
  },
  "upload.error.failed": {
    en: "Upload failed.",
    zh: "上传失败。",
    intent: "Generic upload failure fallback.",
    toneNote: "Short and factual.",
    usageScope: "Upload action error fallback.",
  },
  "upload.error.slow": {
    en: "This upload is taking longer than expected.",
    zh: "上传耗时比预期更长。",
    intent: "Upload polling timeout fallback.",
    toneNote: "Calm and factual.",
    usageScope: "Upload action error fallback.",
  },
  "marks.loading": {
    en: "Loading your marks...",
    zh: "正在加载你的标记...",
    intent: "Marks page loading title.",
    toneNote: "Neutral.",
    usageScope: "Marks page loading card.",
  },
  "marks.error.title": {
    en: "Marks page is unavailable",
    zh: "标记页暂时不可用",
    intent: "Marks page error title.",
    toneNote: "Calm and informative.",
    usageScope: "Marks page error state.",
  },
  "marks.error.message": {
    en: "We could not load your saved marks right now.",
    zh: "当前无法加载已保存的标记。",
    intent: "Marks page error body copy.",
    toneNote: "Calm and informative.",
    usageScope: "Marks page error state.",
  },
  "marks.subtitle": {
    en: "Resonance, blindspot, and bookmark reactions saved across the whole workspace",
    zh: "汇总整个工作区里保存的共鸣、盲点和书签标记。",
    intent: "Marks page subtitle.",
    toneNote: "Explains scope, still concise.",
    usageScope: "Marks page header.",
  },
  "marks.empty.title": {
    en: "No marks yet",
    zh: "还没有标记",
    intent: "Marks page empty headline.",
    toneNote: "Encouraging and concise.",
    usageScope: "Marks page empty state.",
  },
  "marks.empty.message": {
    en: "Review completed chapter pages and use the mark controls on reactions to save them here.",
    zh: "先去浏览已完成章节，并在反应卡片上使用标记按钮，这里就会出现内容。",
    intent: "Marks page empty body copy.",
    toneNote: "Action-guiding.",
    usageScope: "Marks page empty state.",
  },
  "marks.savedSummary": {
    en: "{count} saved marks",
    zh: "{count} 个已保存标记",
    intent: "Per-book saved mark count.",
    toneNote: "Compact and factual.",
    usageScope: "Marks page book grouping header.",
  },
  "marks.action.openBook": {
    en: "Open book",
    zh: "打开本书",
    intent: "Action to open the parent book overview from marks pages.",
    toneNote: "Short and direct.",
    usageScope: "Marks page and grouped book mark panels.",
  },
  "marks.action.openChapter": {
    en: "Open chapter",
    zh: "打开章节",
    intent: "Action to open the parent chapter from marks views.",
    toneNote: "Short and direct.",
    usageScope: "Marks page and grouped book mark panels.",
  },
  "overview.loading": {
    en: "Loading book details...",
    zh: "正在加载书籍详情...",
    intent: "Book overview loading title.",
    toneNote: "Neutral.",
    usageScope: "Book overview loading card.",
  },
  "overview.error.title": {
    en: "Book overview is unavailable",
    zh: "书籍总览暂时不可用",
    intent: "Book overview error title.",
    toneNote: "Calm and informative.",
    usageScope: "Book overview error state.",
  },
  "overview.error.message": {
    en: "We could not load this book right now.",
    zh: "当前无法加载这本书。",
    intent: "Book overview error body copy.",
    toneNote: "Calm and informative.",
    usageScope: "Book overview error state.",
  },
  "overview.error.start": {
    en: "Could not start deep reading.",
    zh: "无法开始深读。",
    intent: "Fallback error after trying to start deep reading from the overview.",
    toneNote: "Short and factual.",
    usageScope: "Book overview start action error state.",
  },
  "overview.error.resume": {
    en: "Could not continue deep reading.",
    zh: "无法继续深读。",
    intent: "Fallback error after trying to resume deep reading from the overview.",
    toneNote: "Short and factual.",
    usageScope: "Book overview resume action error state.",
  },
  "overview.cta.start": {
    en: "Start deep reading",
    zh: "开始深读",
    intent: "Primary CTA for books that have not started reading.",
    toneNote: "Confident primary action.",
    usageScope: "Book overview header actions.",
  },
  "overview.cta.resume": {
    en: "Resume deep reading",
    zh: "继续深读",
    intent: "Primary CTA for paused books.",
    toneNote: "Confident recovery action.",
    usageScope: "Book overview header actions.",
  },
  "overview.cta.resumeUnavailable.generic": {
    en: "This reading run is paused, but there is no usable resume point yet.",
    zh: "这次阅读当前已暂停，但暂时没有可用的继续位置。",
    intent: "Header helper text when a paused run cannot currently be resumed.",
    toneNote: "Honest and calm.",
    usageScope: "Book overview header actions.",
  },
  "overview.cta.resumeUnavailable.runtimeStale": {
    en: "The live runtime went stale and this book has been parked on its last known position.",
    zh: "实时运行状态已经过期，这本书被停在上次已知的位置。",
    intent: "Header helper text when a paused run was downgraded after the runtime heartbeat went stale.",
    toneNote: "Honest, calm, and explanatory.",
    usageScope: "Book overview header actions.",
  },
  "overview.cta.resumeUnavailable.runtimeInterrupted": {
    en: "The reading run was interrupted, so this book is showing the last known position for now.",
    zh: "这次阅读曾被中断，所以当前只显示上次停留的位置。",
    intent: "Header helper text when a paused run was downgraded after an interruption.",
    toneNote: "Honest, calm, and explanatory.",
    usageScope: "Book overview header actions.",
  },
  "overview.cta.resumeUnavailable.resumeIncompatible": {
    en: "This paused run does not match a resumable checkpoint, so it cannot continue from here.",
    zh: "这次暂停运行没有匹配到可续读的 checkpoint，因此当前无法直接继续。",
    intent: "Header helper text when the paused run is not compatible with resume.",
    toneNote: "Honest and specific.",
    usageScope: "Book overview header actions.",
  },
  "overview.cta.resumeUnavailable.devRunAbandoned": {
    en: "This was left behind by a development-only run, so it is shown only as a last known stop.",
    zh: "这是一次开发态遗留运行，因此当前只作为上次停留位置展示。",
    intent: "Header helper text when the paused state comes from a development-only run.",
    toneNote: "Honest and specific.",
    usageScope: "Book overview header actions.",
  },
  "overview.cta.running": {
    en: "Deep reading in progress",
    zh: "深读进行中",
    intent: "Passive running-state badge in the header.",
    toneNote: "Calm, live-status wording.",
    usageScope: "Book overview header actions.",
  },
  "overview.cta.downloadSource": {
    en: "Download source EPUB",
    zh: "下载原始 EPUB",
    intent: "Download action for the uploaded source file.",
    toneNote: "Purely functional.",
    usageScope: "Book overview header actions.",
  },
  "overview.section.readyToStart": {
    en: "Ready to Start",
    zh: "准备开始",
    intent: "Eyebrow label for not-started overview state.",
    toneNote: "Short and energizing.",
    usageScope: "Book overview status band.",
  },
  "overview.ready.title.ready": {
    en: "The original chapter outline is ready",
    zh: "原书目录已就绪",
    intent: "Headline when the base chapter outline is ready before deep reading starts.",
    toneNote: "Factual and reassuring.",
    usageScope: "Not-started book overview state.",
  },
  "overview.ready.title.preparing": {
    en: "Preparing the chapter outline",
    zh: "正在准备目录",
    intent: "Headline when the base chapter outline is still being prepared.",
    toneNote: "Factual and temporary.",
    usageScope: "Not-started book overview state.",
  },
  "overview.ready.description": {
    en: "Semantic segmentation begins automatically after deep reading starts. This page first helps you review the original chapter structure of the book.",
    zh: "语义段落切分会在开始深读后自动进行，当前页先帮助你确认整本书的原始章节结构。",
    intent: "Not-started explanatory copy.",
    toneNote: "Helpful and calm.",
    usageScope: "Not-started book overview state.",
  },
  "overview.metric.parsedChapters": {
    en: "Parsed chapters",
    zh: "已解析章节",
    intent: "Metric label for base chapter outline count.",
    toneNote: "Short and factual.",
    usageScope: "Not-started book overview state.",
  },
  "overview.section.completed": {
    en: "Completed Overview",
    zh: "完成概览",
    intent: "Eyebrow label for completed overview summary.",
    toneNote: "Short and calm.",
    usageScope: "Completed book overview state.",
  },
  "overview.completed.title": {
    en: "Deep reading is complete",
    zh: "深读已完成",
    intent: "Headline for a completed book overview.",
    toneNote: "Clear, calm, and outcome-focused.",
    usageScope: "Completed book overview state.",
  },
  "overview.completed.description": {
    en: "Use the structure below to reopen finished chapters, or revisit the marks you saved along the way.",
    zh: "从下面的结构重新进入已完成章节，或回看你在阅读过程中保存的标记。",
    intent: "Body copy for a completed book overview.",
    toneNote: "Guide-like and outcome-focused.",
    usageScope: "Completed book overview state.",
  },
  "overview.metric.completedChapters": {
    en: "Completed chapters",
    zh: "已完成章节",
    intent: "Metric label for completed chapter count.",
    toneNote: "Short and factual.",
    usageScope: "Completed book overview state.",
  },
  "overview.metric.totalReactions": {
    en: "Reactions surfaced",
    zh: "已产出反应",
    intent: "Metric label for the total surfaced reactions in a book.",
    toneNote: "Short and factual.",
    usageScope: "Completed book overview state and summary rail.",
  },
  "overview.metric.savedMarks": {
    en: "Saved marks",
    zh: "已保存标记",
    intent: "Metric label for saved marks in a book.",
    toneNote: "Short and factual.",
    usageScope: "Completed book overview state and summary rail.",
  },
  "overview.metric.eta": {
    en: "ETA",
    zh: "预计剩余时间",
    intent: "Hero metric label for estimated time remaining.",
    toneNote: "Short and factual.",
    usageScope: "Book overview hero metrics.",
  },
  "overview.metric.resumePoint": {
    en: "Resume point",
    zh: "续读位置",
    intent: "Hero metric label for the latest resumable checkpoint.",
    toneNote: "Short and factual.",
    usageScope: "Book overview hero metrics.",
  },
  "overview.metric.etaUnavailable": {
    en: "ETA unavailable",
    zh: "暂时无法估计剩余时间",
    intent: "Fallback label when the run cannot estimate the remaining time.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime status band.",
  },
  "overview.metric.etaSecondsRemaining": {
    en: "{seconds}s remaining",
    zh: "还剩 {seconds} 秒",
    intent: "Compact ETA label for less than one minute remaining.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime status band.",
  },
  "overview.metric.etaMinutesSecondsRemaining": {
    en: "{minutes}m {seconds}s remaining",
    zh: "还剩 {minutes} 分 {seconds} 秒",
    intent: "Compact ETA label for less than one hour remaining with seconds detail.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime status band.",
  },
  "overview.metric.etaMinutesRemaining": {
    en: "{minutes}m remaining",
    zh: "还剩 {minutes} 分",
    intent: "Compact ETA label for less than one hour remaining.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime status band.",
  },
  "overview.metric.etaHoursMinutesRemaining": {
    en: "{hours}h {minutes}m remaining",
    zh: "还剩 {hours} 小时 {minutes} 分",
    intent: "Compact ETA label for multiple hours remaining with minute detail.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime status band.",
  },
  "overview.metric.etaHoursRemaining": {
    en: "{hours}h remaining",
    zh: "还剩 {hours} 小时",
    intent: "Compact ETA label for multiple hours remaining without minute detail.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime status band.",
  },
  "overview.section.interrupted": {
    en: "Interrupted",
    zh: "处理中断",
    intent: "Eyebrow label for failed or interrupted overview state.",
    toneNote: "Calm but serious.",
    usageScope: "Error book overview state.",
  },
  "overview.error.interruptedTitle": {
    en: "This reading run was interrupted",
    zh: "处理过程已中断",
    intent: "Error-state headline for interrupted reading runs.",
    toneNote: "Calm and factual.",
    usageScope: "Book overview error state.",
  },
  "overview.error.interruptedDescription": {
    en: "Realtime sync is unavailable for this book right now. Try again in a moment, or return to the shelf and reopen it.",
    zh: "这本书目前无法继续同步实时状态，请稍后重试或返回书架重新进入。",
    intent: "Error-state body copy for interrupted runs.",
    toneNote: "Actionable and calm.",
    usageScope: "Book overview error state.",
  },
  "overview.section.runConsole": {
    en: "Reading status",
    zh: "阅读状态",
    intent: "Primary status heading for in-progress runs.",
    toneNote: "Calm, product-like, and clear.",
    usageScope: "Book overview runtime state band.",
  },
  "overview.metric.currentChapter": {
    en: "Current chapter",
    zh: "当前章节",
    intent: "Runtime metric label.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime state band.",
  },
  "overview.metric.currentStep": {
    en: "Current step",
    zh: "当前步骤",
    intent: "Runtime metric label while parsing.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime state band.",
  },
  "overview.metric.currentFocus": {
    en: "Current focus",
    zh: "当前焦点",
    intent: "Runtime metric label while reading.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime state band.",
  },
  "overview.metric.runtimeState": {
    en: "Status",
    zh: "当前状态",
    intent: "Runtime metric label for the top-level reading state.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime state band.",
  },
  "overview.runtime.reactionsSummary": {
    en: "{count} reactions surfaced in this chapter so far",
    zh: "本章当前已产出 {count} 条反应",
    intent: "Expandable reaction summary inside the runtime band.",
    toneNote: "Factual and live.",
    usageScope: "Book overview runtime state band.",
  },
  "overview.runtime.lastCheckpoint": {
    en: "Latest resume point: {value}",
    zh: "最近续读位置：{value}",
    intent: "Resume point timestamp line under the runtime band.",
    toneNote: "Product-like and concise.",
    usageScope: "Book overview runtime state band.",
  },
  "overview.runtime.syncing": {
    en: "Syncing reading status...",
    zh: "正在同步阅读状态...",
    intent: "Transient sync helper text.",
    toneNote: "Short and calm.",
    usageScope: "Book overview runtime state band and runtime panel.",
  },
  "overview.runtime.retry": {
    en: "Retry sync",
    zh: "重试同步",
    intent: "Retry action for runtime polling failures.",
    toneNote: "Short and direct.",
    usageScope: "Book overview runtime band and runtime panel.",
  },
  "overview.runtime.pending": {
    en: "Pending",
    zh: "等待中",
    intent: "Fallback runtime step label before a concrete phase exists.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime band.",
  },
  "overview.runtime.waitingForStructure": {
    en: "Waiting for structure",
    zh: "等待结构就绪",
    intent: "Fallback current chapter value before any chapter is ready.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime band.",
  },
  "overview.runtime.state.paused.label": {
    en: "Paused",
    zh: "已暂停",
    intent: "Runtime-state label when the reading run is paused.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.paused.detail": {
    en: "Deep reading is paused right now. You can resume it from here later.",
    zh: "当前深读流程已暂停，可以稍后从这里继续。",
    intent: "Runtime-state detail when the reading run is paused.",
    toneNote: "Calm and actionable.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.paused.runtimeStale.label": {
    en: "Paused on the last known reading state",
    zh: "停在上次已知的阅读状态",
    intent: "Runtime-state label when an active-looking runtime was downgraded because its heartbeat went stale.",
    toneNote: "Calm and non-live.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.paused.runtimeStale.detail": {
    en: "The live runtime stopped updating, so this page is showing the last known stop instead of a live read.",
    zh: "实时运行状态已经停止更新，因此这里展示的是上次停留的位置，而不是正在发生的阅读。",
    intent: "Runtime-state detail for stale runtime projections.",
    toneNote: "Honest and explanatory.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.paused.runtimeInterrupted.label": {
    en: "Paused after an interruption",
    zh: "中断后暂停",
    intent: "Runtime-state label when the reading run was interrupted and parked.",
    toneNote: "Calm and non-live.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.paused.runtimeInterrupted.detail": {
    en: "This run was interrupted, so the page is holding on to the last known reading position.",
    zh: "这次运行曾被中断，因此当前页面保留的是上次已知的阅读位置。",
    intent: "Runtime-state detail for interrupted runtime projections.",
    toneNote: "Honest and explanatory.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.paused.resumeIncompatible.label": {
    en: "Paused without a resumable checkpoint",
    zh: "已暂停，但没有可续读 checkpoint",
    intent: "Runtime-state label when the paused run cannot resume.",
    toneNote: "Honest and calm.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.paused.resumeIncompatible.detail": {
    en: "The last known position is still visible here, but this run cannot safely continue from it.",
    zh: "这里仍保留了上次已知的位置，但当前无法从那里安全继续。",
    intent: "Runtime-state detail when the paused run cannot resume.",
    toneNote: "Honest and explanatory.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.paused.devRunAbandoned.label": {
    en: "Paused after a development-only run",
    zh: "开发运行结束后暂停",
    intent: "Runtime-state label when the paused state comes from a development-only run.",
    toneNote: "Honest and non-live.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.paused.devRunAbandoned.detail": {
    en: "This page is only keeping the last known stop from an abandoned development run.",
    zh: "当前页面只保留了一次已放弃开发运行留下的最后停留位置。",
    intent: "Runtime-state detail when the paused state comes from a development-only run.",
    toneNote: "Honest and explanatory.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.blocked.label": {
    en: "Reading is blocked",
    zh: "阅读被阻塞",
    intent: "Runtime-state label when reading is waiting for the next chapter to be prepared.",
    toneNote: "Clear and serious.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.blocked.detail": {
    en: "Deep reading will continue after the next chapter finishes segmentation.",
    zh: "等待下一章切分完成后继续深读。",
    intent: "Runtime-state detail when reading is blocked on segmentation.",
    toneNote: "Calm and explanatory.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.preparing.label": {
    en: "Preparing readable chapters",
    zh: "准备可读章节",
    intent: "Runtime-state label before the first chapter is segmented enough to read.",
    toneNote: "Clear and anticipatory.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.preparing.detail": {
    en: "Deep reading will start automatically once the first chapter is segmented.",
    zh: "首章语义切分完成后会自动开始深读。",
    intent: "Runtime-state detail before the first readable chapter is ready.",
    toneNote: "Calm and reassuring.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.segmenting.label": {
    en: "Segmenting",
    zh: "切分中",
    intent: "Runtime-state label while semantic segmentation is actively preparing future reading.",
    toneNote: "Short and tool-like.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.segmenting.detail": {
    en: "Preparing semantic structure for the next reading steps.",
    zh: "正在为后续阅读准备语义结构。",
    intent: "Fallback runtime-state detail while segmenting.",
    toneNote: "Tool-like and factual.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.reading.label": {
    en: "Reading",
    zh: "正在阅读",
    intent: "Runtime-state label while the reader is actively processing text.",
    toneNote: "Short and live.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.reading.detail": {
    en: "Advancing through the current chapter.",
    zh: "正在推进当前章节。",
    intent: "Fallback runtime-state detail while the reader is active.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.running.label": {
    en: "Deep reading in progress",
    zh: "深读进行中",
    intent: "Fallback runtime-state label when the run is active but not in a more specific sub-state.",
    toneNote: "Short and calm.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.state.running.detail": {
    en: "The current chapter is still moving forward.",
    zh: "正在推进当前章节的深读过程。",
    intent: "Fallback runtime-state detail for a generic active run.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime state card.",
  },
  "overview.runtime.currentStep.prefix": {
    en: "Current step: {value}",
    zh: "当前步骤: {value}",
    intent: "Prefix template for chapter navigator and runtime labels that expose the current processing step.",
    toneNote: "Short and factual.",
    usageScope: "Book overview structure navigator.",
  },
  "overview.runtime.currentStep.preparing": {
    en: "Current step: Preparing readable structure",
    zh: "当前步骤: 正在准备可读结构",
    intent: "Fallback current-step label before a concrete parse step exists.",
    toneNote: "Short and factual.",
    usageScope: "Book overview structure navigator.",
  },
  "overview.runtime.currentStatus.prefix": {
    en: "Current state: {value}",
    zh: "当前状态: {value}",
    intent: "Prefix template for chapter navigator runtime context when the reader is active but not focused on a section ref.",
    toneNote: "Short and factual.",
    usageScope: "Book overview structure navigator.",
  },
  "overview.runtime.currentStatus.reading": {
    en: "Current state: Deep reading is active",
    zh: "当前状态: 正在深读",
    intent: "Fallback runtime state line for the current chapter navigator card.",
    toneNote: "Short and factual.",
    usageScope: "Book overview structure navigator.",
  },
  "overview.runtime.lastKnownStatus.prefix": {
    en: "Last known state: {value}",
    zh: "上次状态: {value}",
    intent: "Prefix template for paused or interrupted runtime context that should be rendered as last-known state rather than live state.",
    toneNote: "Short, factual, and explicitly non-live.",
    usageScope: "Book overview structure navigator and runtime side rail.",
  },
  "overview.runtime.lastKnownSection": {
    en: "Last stop: {value}",
    zh: "上次停在: {value}",
    intent: "Last-known section label for paused or interrupted runtime context.",
    toneNote: "Short, factual, and non-live.",
    usageScope: "Book overview structure navigator and runtime side rail.",
  },
  "overview.runtime.lastKnownFocus": {
    en: "Last known focus",
    zh: "上次停留焦点",
    intent: "Fallback last-known runtime label when a paused run has no more specific step or section.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime side rail.",
  },
  "overview.runtime.waitingResume": {
    en: "Waiting to resume reading",
    zh: "等待继续阅读",
    intent: "Status line shown when a completed current chapter is waiting for reading to continue.",
    toneNote: "Short and factual.",
    usageScope: "Book overview structure navigator.",
  },
  "overview.runtime.waitingNext": {
    en: "Waiting for the next chapter to finish segmentation",
    zh: "等待下一章切分完成",
    intent: "Status line shown when reading is blocked on the next chapter.",
    toneNote: "Short and factual.",
    usageScope: "Book overview structure navigator.",
  },
  "overview.runtime.readingSection": {
    en: "Reading: {value}",
    zh: "正在阅读: {value}",
    intent: "Status line for the current section inside the active chapter.",
    toneNote: "Short and live.",
    usageScope: "Book overview structure navigator.",
  },
  "overview.section.explore": {
    en: "Explore this book",
    zh: "探索这本书",
    intent: "Eyebrow label for the mode switch section.",
    toneNote: "Guide-like and calm.",
    usageScope: "Book overview mode switcher.",
  },
  "overview.structure.emptyNotReady": {
    en: "Book structure is not ready yet",
    zh: "书籍结构暂未准备好",
    intent: "Structure empty-state title before the outline exists.",
    toneNote: "Calm and factual.",
    usageScope: "Book overview structure area.",
  },
  "overview.structure.emptyNotReadyMessage": {
    en: "The book was added, but the parsed chapter structure is not available yet.",
    zh: "这本书已经加入书架，但解析后的章节结构暂时还不可用。",
    intent: "Structure empty-state body before the outline exists.",
    toneNote: "Calm and factual.",
    usageScope: "Book overview structure area.",
  },
  "overview.structure.emptyProgress": {
    en: "No chapters are available yet",
    zh: "还没有可显示的章节",
    intent: "Structure empty-state title while runtime views are still empty.",
    toneNote: "Calm and factual.",
    usageScope: "Book overview structure area.",
  },
  "overview.structure.emptyProgressMessage": {
    en: "Chapter-level structure will appear here as the parser and reader make progress.",
    zh: "随着解析和阅读推进，章节结构会显示在这里。",
    intent: "Structure empty-state body while runtime views are still empty.",
    toneNote: "Calm and forward-looking.",
    usageScope: "Book overview structure area.",
  },
  "overview.structure.openCompletedChapter": {
    en: "Open completed chapter",
    zh: "打开已完成章节",
    intent: "CTA hint for completed chapters in structure views.",
    toneNote: "Short and direct.",
    usageScope: "Book overview structure lists and runtime navigator.",
  },
  "overview.structure.expand": {
    en: "Expand",
    zh: "展开",
    intent: "Action label for collapsed mobile structure panel.",
    toneNote: "Short and direct.",
    usageScope: "Book overview mobile structure navigator.",
  },
  "overview.structure.mobileHint": {
    en: "Open completed chapters here and keep the live position in view.",
    zh: "从这里打开已完成章节，并保持当前进度在视野中。",
    intent: "Support copy for collapsed mobile structure panel.",
    toneNote: "Helpful and concise.",
    usageScope: "Book overview mobile structure navigator.",
  },
  "overview.structure.desktopHint": {
    en: "Open completed chapters first and keep the current position pinned.",
    zh: "优先从这里进入已完成章节，并持续追踪当前位置。",
    intent: "Support copy for desktop structure navigator.",
    toneNote: "Helpful and concise.",
    usageScope: "Book overview desktop structure navigator.",
  },
  "overview.marks.emptyTitle": {
    en: "No marks for this book yet",
    zh: "这本书还没有标记",
    intent: "Book-scoped marks empty-state title.",
    toneNote: "Calm and factual.",
    usageScope: "Book overview marks tab.",
  },
  "overview.marks.emptyMessage": {
    en: "Resonance, blindspot, and bookmark marks will appear here as soon as you save them from completed chapters.",
    zh: "当你在已完成章节里保存共鸣、盲点或书签标记后，它们会出现在这里。",
    intent: "Book-scoped marks empty-state body.",
    toneNote: "Helpful and forward-looking.",
    usageScope: "Book overview marks tab.",
  },
  "overview.summary.title": {
    en: "Book at a glance",
    zh: "全书一览",
    intent: "Compact summary card title shown beside completed structure results.",
    toneNote: "Short and guide-like.",
    usageScope: "Completed book overview supporting rail.",
  },
  "overview.marks.summaryTitle": {
    en: "My Marks",
    zh: "我的标记",
    intent: "Compact marks summary card title in the book overview.",
    toneNote: "Short and familiar.",
    usageScope: "Completed book overview supporting rail.",
  },
  "overview.marks.summaryReady": {
    en: "{count} saved marks are ready to revisit from completed chapters.",
    zh: "你保存的 {count} 个标记已经可以从已完成章节中重新回看。",
    intent: "Supporting copy when a completed book already has saved marks.",
    toneNote: "Helpful and encouraging.",
    usageScope: "Completed book overview supporting rail.",
  },
  "overview.marks.summaryEmpty": {
    en: "No marks from this book yet. Save a few from completed chapters to collect them here.",
    zh: "这本书还没有标记。你可以从已完成章节里保存一些内容，稍后集中回看。",
    intent: "Supporting copy when a completed book has no saved marks yet.",
    toneNote: "Helpful and forward-looking.",
    usageScope: "Completed book overview supporting rail.",
  },
  "overview.marks.summaryAction": {
    en: "Open My Marks",
    zh: "打开我的标记",
    intent: "Action from the completed overview supporting rail into the marks tab.",
    toneNote: "Short and direct.",
    usageScope: "Completed book overview supporting rail.",
  },
  "overview.mindstream.title": {
    en: "Reading mindstream",
    zh: "阅读心流",
    intent: "Main runtime narrative panel title.",
    toneNote: "Productive and evocative.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.empty": {
    en: "Waiting for the first visible thought.",
    zh: "等待第一条可见思路浮现。",
    intent: "Empty-state copy for visible mindstream events.",
    toneNote: "Quiet and minimal.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.paused.generic": {
    en: "Deep reading is paused on this last known stop",
    zh: "深读停在这里的上次停留点上",
    intent: "Mindstream headline when the run is paused and the panel should describe a last-known stop.",
    toneNote: "Calm and non-live.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.paused.runtimeStale": {
    en: "The live runtime went stale, so this is the last known reading stop",
    zh: "实时运行状态已经过期，所以这里显示的是上次停留的位置",
    intent: "Mindstream headline for stale paused runtime projections.",
    toneNote: "Honest and non-live.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.paused.runtimeInterrupted": {
    en: "This run was interrupted, so the panel is holding the last known stop",
    zh: "这次运行曾被中断，所以这里保留的是上次停留的位置",
    intent: "Mindstream headline for interrupted paused runtime projections.",
    toneNote: "Honest and non-live.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.paused.resumeIncompatible": {
    en: "This paused run cannot resume, but its last known stop is still visible here",
    zh: "这次暂停运行无法继续，但它上次停留的位置仍然保留在这里",
    intent: "Mindstream headline for paused runs without a resumable checkpoint.",
    toneNote: "Honest and non-live.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.paused.devRunAbandoned": {
    en: "This development-only run was abandoned, so only its last known stop remains here",
    zh: "这次开发态运行已经放弃，因此这里只保留它最后停留的位置",
    intent: "Mindstream headline for paused development-only runs.",
    toneNote: "Honest and non-live.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.live.reading.default": {
    en: "Reading the next line",
    zh: "正在读下一句",
    intent: "Default live-activity line while the reader is taking in the next sentence.",
    toneNote: "Clear, calm, and quietly alive.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.reading.alternate": {
    en: "Taking in a sentence",
    zh: "正在读进这句话",
    intent: "Alternate live-activity line while the reader is still with the current sentence.",
    toneNote: "Clear, lyrical, and quietly alive.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.reading.still": {
    en: "Still with the line",
    zh: "还在这句话里",
    intent: "Slow-phase live-activity line while reading continues without a stage change.",
    toneNote: "Acknowledges duration without sounding broken.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.thinking.default": {
    en: "Turning a line over",
    zh: "正在反复咂摸这句话",
    intent: "Generic live-activity line for active thinking before a clearer thought family emerges.",
    toneNote: "Clear, lyrical, and in-progress.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.thinking.discern": {
    en: "Turning a claim over",
    zh: "正在反复推敲一个说法",
    intent: "Live-activity line for a discern-style thinking phase.",
    toneNote: "Clear, incisive, and in-progress.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.thinking.association": {
    en: "Following a resonance",
    zh: "正在顺着一阵回响追下去",
    intent: "Live-activity line for an association-style thinking phase.",
    toneNote: "Clear, connective, and quietly alive.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.thinking.curious": {
    en: "Following a question",
    zh: "正在顺着一个问题走下去",
    intent: "Live-activity line for a curious thinking phase before search begins.",
    toneNote: "Clear, curious, and in-progress.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.thinking.retrospect": {
    en: "Returning to an earlier thread",
    zh: "正在回到前面的线索上",
    intent: "Live-activity line for a retrospect-style thinking phase.",
    toneNote: "Clear, reflective, and in-progress.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.thinking.highlight": {
    en: "Staying with a line",
    zh: "正在留住一句话",
    intent: "Live-activity line for a highlight-style thinking phase.",
    toneNote: "Clear, attentive, and in-progress.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.thinking.still": {
    en: "Still turning it over",
    zh: "还在反复推敲",
    intent: "Slow-phase live-activity line while thinking remains active.",
    toneNote: "Acknowledges duration without sounding stalled.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.searching.default": {
    en: "Looking into a question",
    zh: "正在查一个问题",
    intent: "Default live-activity line while the reader is searching.",
    toneNote: "Clear, investigative, and in-progress.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.searching.curious": {
    en: "Pulling on a thread",
    zh: "正在顺着一条线索往下拉",
    intent: "Alternate live-activity line for curiosity-driven searching.",
    toneNote: "Clear, curious, and quietly alive.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.searching.still": {
    en: "Still looking into it",
    zh: "还在往下查",
    intent: "Slow-phase live-activity line while search work continues.",
    toneNote: "Acknowledges duration without sounding alarmed.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.fusing.default": {
    en: "Working the thread further",
    zh: "正在把这条线索继续编下去",
    intent: "Default live-activity line while the reader fuses new material into the current thought.",
    toneNote: "Clear, connective, and in-progress.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.fusing.alternate": {
    en: "Bringing the pieces together",
    zh: "正在把零散的东西接起来",
    intent: "Alternate live-activity line while the reader integrates search/context back into the thought.",
    toneNote: "Clear, connective, and quietly active.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.fusing.still": {
    en: "Still bringing it together",
    zh: "还在把它接起来",
    intent: "Slow-phase live-activity line while the reader is still integrating the thread.",
    toneNote: "Acknowledges duration without sounding mechanical.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.reflecting.default": {
    en: "Checking what holds",
    zh: "正在看什么还能站得住",
    intent: "Default live-activity line while the reader reflects on a thought.",
    toneNote: "Clear, reflective, and in-progress.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.reflecting.alternate": {
    en: "Seeing what survives",
    zh: "正在看最后留下了什么",
    intent: "Alternate live-activity line while the reader tests what remains after reflection.",
    toneNote: "Clear, reflective, and quietly alive.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.reflecting.still": {
    en: "Still checking what holds",
    zh: "还在看什么站得住",
    intent: "Slow-phase live-activity line while reflection remains active.",
    toneNote: "Acknowledges duration without sounding stalled.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.waiting.default": {
    en: "Waiting for the next chapter",
    zh: "正在等待下一章准备好",
    intent: "Live-activity line when the reader is blocked waiting for preparation work.",
    toneNote: "Clear and patient.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.preparing.default": {
    en: "Preparing the next chapter",
    zh: "正在准备下一章",
    intent: "Live-activity line when the reader is still preparing readable structure.",
    toneNote: "Clear and patient.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.problem.default": {
    en: "Still working through this",
    zh: "还在处理这一处",
    intent: "Generic degraded live-activity line when the current phase has gone stale without a clearer error category.",
    toneNote: "Calm, honest, and non-alarming.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.problem.llm_timeout": {
    en: "Retrying the model call",
    zh: "正在重试模型调用",
    intent: "Degraded live-activity line when the model request timed out.",
    toneNote: "Clear and action-oriented without panic.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.problem.llm_quota": {
    en: "The model is out of room right now",
    zh: "模型额度暂时耗尽了",
    intent: "Degraded live-activity line when the model quota has been exhausted.",
    toneNote: "Honest and calm.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.problem.llm_auth": {
    en: "The model needs attention",
    zh: "模型访问需要处理",
    intent: "Degraded live-activity line when model authentication fails.",
    toneNote: "Calm and diagnostic.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.problem.search_timeout": {
    en: "Search is taking too long",
    zh: "搜索这会儿太慢了",
    intent: "Degraded live-activity line when search requests time out.",
    toneNote: "Calm and lightly diagnostic.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.problem.search_quota": {
    en: "Search is out of room right now",
    zh: "搜索额度暂时耗尽了",
    intent: "Degraded live-activity line when search quota has been exhausted.",
    toneNote: "Honest and calm.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.problem.search_auth": {
    en: "Search needs attention",
    zh: "搜索访问需要处理",
    intent: "Degraded live-activity line when search authentication fails.",
    toneNote: "Calm and diagnostic.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.live.problem.network_blocked": {
    en: "Waiting on the connection",
    zh: "正在等连接恢复",
    intent: "Degraded live-activity line when the reader is blocked by network conditions.",
    toneNote: "Calm and transparent.",
    usageScope: "Book overview mindstream live activity.",
  },
  "overview.mindstream.moreThoughts": {
    en: "+{count} more thoughts",
    zh: "+{count} 条延伸思路",
    intent: "Expand control for additional reactions attached to one sentence-level moment.",
    toneNote: "Light and literary.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.hideExtraThoughts": {
    en: "Hide extra thoughts",
    zh: "收起延伸思路",
    intent: "Collapse control for additional reactions attached to one sentence-level moment.",
    toneNote: "Light and calm.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.openInChapterTooltip": {
    en: "Open the chapter workspace",
    zh: "打开章节工作区",
    intent: "Tooltip and aria label for the icon-only jump from one mindstream moment into a completed chapter.",
    toneNote: "Quiet and actionable.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.openInChapter": {
    en: "Open in chapter",
    zh: "在章节中查看",
    intent: "Secondary link from one mindstream moment into the completed chapter result.",
    toneNote: "Quiet and actionable.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.liveNow": {
    en: "Live now",
    zh: "此刻",
    intent: "Eyebrow label for the live stage inside the in-progress mindstream hero.",
    toneNote: "Clear and present.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.lastKnownNow": {
    en: "Last known stop",
    zh: "上次停留",
    intent: "Eyebrow label for the current paused last-known mindstream state.",
    toneNote: "Clear and explicitly non-live.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.recentTrail": {
    en: "Recent trail",
    zh: "最近轨迹",
    intent: "Section label for the collapsed/expanded historical trail inside the in-progress mindstream hero.",
    toneNote: "Quiet and secondary.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.showRecentTrail": {
    en: "Show recent trail",
    zh: "展开最近轨迹",
    intent: "Button label to expand the recent trail within the mindstream hero.",
    toneNote: "Quiet and inviting.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.hideRecentTrail": {
    en: "Hide recent trail",
    zh: "收起最近轨迹",
    intent: "Button label to collapse the recent trail within the mindstream hero.",
    toneNote: "Quiet and calm.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.trailEmpty": {
    en: "No visible trail yet. The first surfaced thought will appear here.",
    zh: "还没有可见轨迹，第一条浮现出来的思路会出现在这里。",
    intent: "Empty-state copy for the recent trail section inside the in-progress mindstream hero.",
    toneNote: "Quiet and patient.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.meta.moveType.label": {
    en: "Move",
    zh: "当前动作",
    intent: "Compact label for the current attentional move chip in the live mindstream panel.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.meta.moveType.advance": {
    en: "Advancing",
    zh: "推进中",
    intent: "Compact value for the advance move type.",
    toneNote: "Short and active.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.meta.moveType.dwell": {
    en: "Dwelling",
    zh: "停驻中",
    intent: "Compact value for the dwell move type.",
    toneNote: "Short and active.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.meta.moveType.bridge": {
    en: "Bridging",
    zh: "回桥中",
    intent: "Compact value for the bridge move type.",
    toneNote: "Short and active.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.meta.moveType.reframe": {
    en: "Reframing",
    zh: "重构中",
    intent: "Compact value for the reframe move type.",
    toneNote: "Short and active.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.meta.activeThought.label": {
    en: "Focused thought",
    zh: "当前思路",
    intent: "Compact label for the active thought chip in the live mindstream panel.",
    toneNote: "Short and factual.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.meta.activeThought.value": {
    en: "#{id}",
    zh: "#{id}",
    intent: "Compact value showing the public reaction id of the active thought.",
    toneNote: "Technical but concise.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.meta.activeThought.open": {
    en: "Open the current thought in the chapter view",
    zh: "在章节页打开当前思路",
    intent: "Tooltip for the active thought chip when it links to the chapter view.",
    toneNote: "Short and directional.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.locus.title": {
    en: "Where the attention is",
    zh: "注意力所在",
    intent: "Desktop sidecar title for the current reading locus beside the live mindstream.",
    toneNote: "Quiet, editorial, and spatial.",
    usageScope: "Book overview mindstream desktop sidecar.",
  },
  "overview.mindstream.locus.chapter": {
    en: "Chapter",
    zh: "章节",
    intent: "Label for the current chapter reference inside the desktop reading-locus sidecar.",
    toneNote: "Short and factual.",
    usageScope: "Book overview mindstream desktop sidecar.",
  },
  "overview.mindstream.locus.section": {
    en: "Section",
    zh: "小节",
    intent: "Label for the current section or segment reference inside the desktop reading-locus sidecar.",
    toneNote: "Short and factual.",
    usageScope: "Book overview mindstream desktop sidecar.",
  },
  "overview.mindstream.locus.empty": {
    en: "The reading locus will settle here as the next passage comes into focus.",
    zh: "当下一段内容进入焦点时，阅读落点会出现在这里。",
    intent: "Fallback copy when no chapter or section reference is currently available for the reading-locus sidecar.",
    toneNote: "Calm, quiet, and anticipatory.",
    usageScope: "Book overview mindstream desktop sidecar.",
  },
  "overview.mindstream.locus.detail": {
    en: "A soft marker of where the thread is currently dwelling.",
    zh: "一个轻柔的标记，提示这条思路此刻停留在哪里。",
    intent: "Supporting descriptor beneath the reading-locus sidecar content.",
    toneNote: "Editorial, calm, and non-technical.",
    usageScope: "Book overview mindstream desktop sidecar.",
  },
  "overview.mindstream.trace.discern.default": {
    en: "A claim drew pressure",
    zh: "一个说法承受了推敲",
    intent: "Historical label for a discern reaction once it has moved out of the current thread.",
    toneNote: "Quiet, reflective, and complete.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.trace.discern.question": {
    en: "A question opened",
    zh: "一个问题被打开了",
    intent: "Historical label for a discern reaction framed as an opened question.",
    toneNote: "Quiet, reflective, and complete.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.trace.association.default": {
    en: "A connection surfaced",
    zh: "一条连接浮现了出来",
    intent: "Historical label for an association reaction once it has moved into the trace rail.",
    toneNote: "Quiet and literary.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.trace.association.echo": {
    en: "An echo appeared",
    zh: "一道回响浮现了",
    intent: "Historical label for an association reaction that echoes earlier pages.",
    toneNote: "Quiet and literary.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.trace.curious.default": {
    en: "A thread opened",
    zh: "一条线索被打开了",
    intent: "Historical label for a curious reaction after it moves into the trace rail.",
    toneNote: "Light, active, and complete.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.trace.curious.search": {
    en: "A question kept pulling",
    zh: "一个问题一直牵着它",
    intent: "Historical label for a curious reaction that triggered a search.",
    toneNote: "Light, active, and complete.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.trace.retrospect.default": {
    en: "An earlier thread returned",
    zh: "前面的线索又回来了",
    intent: "Historical label for a retrospect reaction after it moves into the trace rail.",
    toneNote: "Quiet and reflective.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.trace.retrospect.echo": {
    en: "Something from before resurfaced",
    zh: "前面的东西又浮了上来",
    intent: "Historical label for a retrospect reaction that clearly recalls an earlier line.",
    toneNote: "Quiet and reflective.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.mindstream.trace.highlight.default": {
    en: "A line stayed with it",
    zh: "一句话留在了心里",
    intent: "Historical label for a highlight-only moment in the trace rail.",
    toneNote: "Quiet and attentive.",
    usageScope: "Book overview runtime panel.",
  },
  "overview.syncError.default": {
    en: "Realtime state is temporarily unavailable.",
    zh: "实时状态暂时不可用。",
    intent: "Fallback runtime sync error body.",
    toneNote: "Calm and factual.",
    usageScope: "Book overview runtime panel.",
  },
  "system.stage.queued": {
    en: "Queued",
    zh: "等待开始",
    intent: "Structured top-status label for queued jobs.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.stage.parsingStructure": {
    en: "Parsing book structure",
    zh: "正在解析书籍结构",
    intent: "Structured top-status label while the base book structure is being prepared.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.stage.parsingChapter": {
    en: "Parsing {chapter}",
    zh: "正在解析 {chapter}",
    intent: "Structured top-status label while parsing a specific chapter into readable structure.",
    toneNote: "Short and live.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.stage.ready": {
    en: "Structure is ready",
    zh: "结构已就绪",
    intent: "Structured top-status label when the base structure has been parsed.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.stage.deepReadingChapter": {
    en: "Reading {chapter}",
    zh: "正在分析 {chapter}",
    intent: "Structured top-status label while deep reading a specific chapter.",
    toneNote: "Short and live.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.stage.deepReading": {
    en: "Deep reading in progress",
    zh: "正在顺序深读",
    intent: "Structured top-status label while deep reading without a specific chapter ref.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.stage.chapterNoteGeneration": {
    en: "Writing chapter notes",
    zh: "正在生成章节笔记",
    intent: "Structured top-status label while generating chapter notes.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.stage.paused": {
    en: "Paused, ready to resume",
    zh: "已暂停，可继续",
    intent: "Structured top-status label for a paused reading run.",
    toneNote: "Short and actionable.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.stage.completed": {
    en: "Completed",
    zh: "全部完成",
    intent: "Structured top-status label for a completed reading run.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.stage.error": {
    en: "Interrupted",
    zh: "分析中断",
    intent: "Structured top-status label for interrupted runs.",
    toneNote: "Short and serious.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.step.waitingToResume": {
    en: "Waiting to resume",
    zh: "等待继续执行",
    intent: "Structured runtime-step label for paused runs awaiting resume.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.step.prepareChapterStructure": {
    en: "Preparing chapter structure",
    zh: "准备章节结构",
    intent: "Structured runtime-step label before semantic segmentation builds chapter structure.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.step.segmenting": {
    en: "Segmenting semantically",
    zh: "语义切分中",
    intent: "Structured runtime-step label during semantic segmentation.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.step.structureCheckpointSaved": {
    en: "Structure checkpoint saved",
    zh: "已保存结构 checkpoint",
    intent: "Structured runtime-step label after a structure checkpoint is written.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.step.structureParseFailed": {
    en: "Structure parsing failed",
    zh: "结构解析失败",
    intent: "Structured runtime-step label for parse failure.",
    toneNote: "Short and serious.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.step.waitingCurrentChapterSegmentation": {
    en: "Waiting for the current chapter to finish segmentation",
    zh: "等待当前章节切分完成",
    intent: "Structured runtime-step label while the reader waits on the current chapter segmentation.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.step.prefetchFutureChapters": {
    en: "Preparing future chapters in the background",
    zh: "后台准备后续章节",
    intent: "Structured runtime-step label while background segmentation prefetches later chapters.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.step.prepareFirstChapter": {
    en: "Preparing the first readable chapter",
    zh: "为首章准备语义结构",
    intent: "Structured runtime-step label before the first chapter is ready to read.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.step.waitingFirstChapterSegmentation": {
    en: "Waiting for the first chapter to finish segmentation",
    zh: "等待首章切分",
    intent: "Structured runtime-step label while waiting for the first chapter to become readable.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "system.step.waitingNextChapterSegmentation": {
    en: "Waiting for the next chapter to finish segmentation",
    zh: "等待后续章节切分",
    intent: "Structured runtime-step label while waiting for a future chapter to become readable.",
    toneNote: "Short and factual.",
    usageScope: "Top runtime status surfaces.",
  },
  "chapter.tooltip.prevChapter": {
    en: "Previous chapter",
    zh: "上一章",
    intent: "Tooltip for previous-chapter navigation.",
    toneNote: "Purely functional.",
    usageScope: "Chapter reading toolbar.",
  },
  "chapter.tooltip.nextChapter": {
    en: "Next chapter",
    zh: "下一章",
    intent: "Tooltip for next-chapter navigation.",
    toneNote: "Purely functional.",
    usageScope: "Chapter reading toolbar.",
  },
  "chapter.tooltip.prevSection": {
    en: "Previous section",
    zh: "上一段",
    intent: "Tooltip for previous-section navigation.",
    toneNote: "Purely functional.",
    usageScope: "Chapter reading toolbar.",
  },
  "chapter.tooltip.nextSection": {
    en: "Next section",
    zh: "下一段",
    intent: "Tooltip for next-section navigation.",
    toneNote: "Purely functional.",
    usageScope: "Chapter reading toolbar.",
  },
  "chapter.loading": {
    en: "Loading chapter workspace...",
    zh: "正在加载章节工作区...",
    intent: "Loading title for the chapter reading workspace.",
    toneNote: "Neutral and functional.",
    usageScope: "Chapter reading loading state.",
  },
  "chapter.error.title": {
    en: "Chapter workspace is unavailable",
    zh: "章节工作区暂时不可用",
    intent: "Error title when the chapter reading workspace cannot load.",
    toneNote: "Calm and informative.",
    usageScope: "Chapter reading error state.",
  },
  "chapter.error.message": {
    en: "We could not load this chapter right now.",
    zh: "当前无法加载这个章节。",
    intent: "Error body copy when the chapter reading workspace cannot load.",
    toneNote: "Calm and informative.",
    usageScope: "Chapter reading error state.",
  },
  "chapter.error.backToBooks": {
    en: "Back to books",
    zh: "返回书架",
    intent: "Recovery link from chapter reading errors back to the bookshelf.",
    toneNote: "Short and directional.",
    usageScope: "Chapter reading error state.",
  },
  "chapter.filter.all": {
    en: "All",
    zh: "全部",
    intent: "Filter label that shows every reaction type.",
    toneNote: "Short and utilitarian.",
    usageScope: "Chapter reading filter rail.",
  },
  "chapter.reader.originalBookFallback": {
    en: "Original book",
    zh: "原书",
    intent: "Fallback title when the original book title is missing in the reader workspace.",
    toneNote: "Neutral and descriptive.",
    usageScope: "Chapter reading workspace and source reader.",
  },
  "chapter.reader.bookProgress": {
    en: "Book {value}",
    zh: "全书 {value}",
    intent: "Compact book-level reading progress badge in the chapter toolbar.",
    toneNote: "Short and factual.",
    usageScope: "Chapter reading toolbar.",
  },
  "chapter.reader.bookProgressUnavailable": {
    en: "Book progress pending",
    zh: "全书进度待更新",
    intent: "Fallback label when book-level progress is not yet available.",
    toneNote: "Calm and factual.",
    usageScope: "Chapter reading toolbar.",
  },
  "chapter.reader.settingsAria": {
    en: "Reading settings",
    zh: "阅读设置",
    intent: "Accessible label for the chapter reading settings trigger.",
    toneNote: "Purely functional.",
    usageScope: "Chapter reading toolbar.",
  },
  "chapter.reader.settingsTitle": {
    en: "Reading text size",
    zh: "阅读文字大小",
    intent: "Title for the chapter reading settings popover.",
    toneNote: "Short and functional.",
    usageScope: "Chapter reading settings popover.",
  },
  "chapter.reader.settingsDescription": {
    en: "Applies to both reactions and the original book.",
    zh: "同时应用于反应侧和原书侧。",
    intent: "Supporting description for the reading settings popover.",
    toneNote: "Helpful and concise.",
    usageScope: "Chapter reading settings popover.",
  },
  "chapter.reader.tabReactions": {
    en: "Reactions",
    zh: "反应",
    intent: "Tab label for the reactions panel in mobile chapter reading.",
    toneNote: "Short and utilitarian.",
    usageScope: "Chapter reading mobile tabs.",
  },
  "chapter.reader.tabOriginalBook": {
    en: "Original book",
    zh: "原书",
    intent: "Tab label for the source reader panel in mobile chapter reading.",
    toneNote: "Short and utilitarian.",
    usageScope: "Chapter reading mobile tabs.",
  },
  "chapter.reader.loadingSource": {
    en: "Loading source EPUB...",
    zh: "正在加载原始 EPUB...",
    intent: "Loading text shown while the source reader initializes.",
    toneNote: "Functional and calm.",
    usageScope: "Source reader pane.",
  },
  "chapter.reader.loadingSourceSlow": {
    en: "Still opening the source EPUB. If this keeps hanging, reload the chapter.",
    zh: "还在打开原始 EPUB；如果持续卡住，可以刷新这个章节。",
    intent: "Slow-loading helper text when the source reader is taking longer than expected to initialize.",
    toneNote: "Calm and honest.",
    usageScope: "Source reader pane.",
  },
  "chapter.reader.unavailableTitle": {
    en: "Source reader unavailable",
    zh: "原书阅读器暂不可用",
    intent: "Title shown when the source reader cannot be opened.",
    toneNote: "Clear and calm.",
    usageScope: "Source reader pane.",
  },
  "chapter.reader.unavailableMissingSource": {
    en: "This book does not currently expose a source EPUB for the reader pane.",
    zh: "这本书当前没有向原书阅读器提供可打开的 EPUB 源文件。",
    intent: "Message shown when the chapter view has no source asset URL.",
    toneNote: "Calm and factual.",
    usageScope: "Source reader pane.",
  },
  "chapter.reader.unavailableTimeout": {
    en: "Opening the source EPUB took too long, so the reader pane stopped waiting.",
    zh: "打开原始 EPUB 用时过久，阅读器面板已停止继续等待。",
    intent: "Message shown when source reader initialization times out.",
    toneNote: "Honest and calm.",
    usageScope: "Source reader pane.",
  },
  "chapter.reader.unavailableGeneric": {
    en: "We could not open the source EPUB for this chapter right now.",
    zh: "当前无法为这个章节打开原始 EPUB。",
    intent: "Fallback message shown when source reader initialization fails for a general reason.",
    toneNote: "Calm and factual.",
    usageScope: "Source reader pane.",
  },
  "chapter.sheet.backToChapters": {
    en: "Chapters",
    zh: "章节",
    intent: "Back action in the mobile chapter sheet from section preview to chapter list.",
    toneNote: "Short and directional.",
    usageScope: "Chapter sheet mobile navigation.",
  },
  "chapter.sheet.status.current": {
    en: "Current",
    zh: "当前",
    intent: "Status label for the chapter currently open in the reading workspace.",
    toneNote: "Short and factual.",
    usageScope: "Chapter sheet chapter list.",
  },
  "chapter.sheet.status.pending": {
    en: "Pending",
    zh: "待完成",
    intent: "Status label for a chapter whose result is not ready yet.",
    toneNote: "Short and factual.",
    usageScope: "Chapter sheet chapter list.",
  },
  "chapter.sheet.status.error": {
    en: "Error",
    zh: "出错",
    intent: "Status label for a chapter whose result failed to prepare.",
    toneNote: "Short and serious.",
    usageScope: "Chapter sheet chapter list.",
  },
  "chapter.sheet.status.completed": {
    en: "Completed",
    zh: "已完成",
    intent: "Status label for a chapter whose result is ready to open.",
    toneNote: "Short and factual.",
    usageScope: "Chapter sheet chapter list.",
  },
  "chapter.sheet.structureBadge": {
    en: "Structure",
    zh: "结构",
    intent: "Small badge indicating a heading block inside the chapter outline.",
    toneNote: "Short and descriptive.",
    usageScope: "Chapter sheet outline heading block.",
  },
  "chapter.sheet.emptySections": {
    en: "No semantic sections available.",
    zh: "还没有可用的语义段落。",
    intent: "Empty-state text when a chapter outline has no semantic sections.",
    toneNote: "Calm and factual.",
    usageScope: "Chapter sheet section previews.",
  },
  "chapter.sheet.inThisChapter": {
    en: "In this chapter",
    zh: "本章结构",
    intent: "Eyebrow label for the chapter outline preview column.",
    toneNote: "Short and descriptive.",
    usageScope: "Chapter sheet desktop preview panel.",
  },
  "chapter.sheet.previewFallback": {
    en: "Chapter preview",
    zh: "章节预览",
    intent: "Fallback title for the chapter outline preview panel.",
    toneNote: "Neutral and descriptive.",
    usageScope: "Chapter sheet desktop preview panel.",
  },
  "chapter.sheet.loadingOutline": {
    en: "Loading chapter outline...",
    zh: "正在加载章节结构...",
    intent: "Loading copy while the chapter outline preview is fetched.",
    toneNote: "Neutral and functional.",
    usageScope: "Chapter sheet desktop preview panel.",
  },
  "chapter.sheet.notReadyTitle": {
    en: "This chapter is not ready yet.",
    zh: "这个章节暂时还不可用。",
    intent: "Headline when a chapter result is not ready for section-level navigation.",
    toneNote: "Calm and factual.",
    usageScope: "Chapter sheet desktop preview panel.",
  },
  "chapter.sheet.notReadyMessage": {
    en: "Finish analysis in the book overview before using section-level navigation here.",
    zh: "请先在书籍总览中完成分析，再来这里使用段落级导航。",
    intent: "Supporting text when a chapter result is not ready for section-level navigation.",
    toneNote: "Helpful and directive.",
    usageScope: "Chapter sheet desktop preview panel.",
  },
} as const satisfies Record<string, ControlledCopyEntry>;

export type ControlledCopyKey = keyof typeof CONTROLLED_COPY;

export function copy(key: ControlledCopyKey, params?: Record<string, string | number | null | undefined>): string {
  return formatTemplate(resolveLocalizedText(CONTROLLED_COPY[key], APP_LOCALE), params);
}

export function copyForLocale(
  key: ControlledCopyKey,
  locale: AppLocale,
  params?: Record<string, string | number | null | undefined>,
): string {
  return formatTemplate(resolveLocalizedText(CONTROLLED_COPY[key], locale), params);
}

export function maybeCopy(
  key: string | null | undefined,
  params?: Record<string, string | number | null | undefined>,
): string | null {
  if (!key || !(key in CONTROLLED_COPY)) {
    return null;
  }
  return copy(key as ControlledCopyKey, params);
}

export function localizedText(text: LocalizedText): string {
  return resolveLocalizedText(text, APP_LOCALE);
}
